import Mathlib
open MeasureTheory ProbabilityTheory

#check @MeasureTheory.integral_finsetSum
#check @MeasureTheory.integral_finset_sum
#check @MeasureTheory.integral_sub_right_eq_self
#check @LinearMap.ker_eq_bot
#check @Matrix.mulVecLin
#check @Matrix.coe_mulVecLin
#check @Matrix.det_ne_zero_of_sum_row_lt_diag
#check @MonovaryOn.sum_mul_sum_le_card_mul_sum
#check @AntivaryOn.card_mul_sum_le_sum_mul_sum
#check @intermediate_value_Icc
#check @ProbabilityTheory.integral_cauchyPDFReal_eq_one
#check @ProbabilityTheory.integral_gaussianPDFReal_eq_one
#check @MeasureTheory.integral_convolution
#check @ProbabilityTheory.gaussianReal_conv_gaussianReal
#check @MeasureTheory.conv_withDensity_eq_lconvolution
#check @convexOn_zpow
#check @ContractingWith.dist_fixedPoint_le
#check @ContractingWith.efixedPoint
#check @Matrix.IsHermitian.eigenvalues
#check @ProbabilityTheory.measure_sum_ge_le_of_iIndepFun
#check @ProbabilityTheory.variance_sum
#check @integral_gaussian
#check @Continuous.ae_eq_iff_eq
#check @Matrix.rank_transpose_mul_self
#check @HasStrictFDerivAt.implicitFunction
#check @Finset.inner_mul_le_norm_mul_norm
#check @Finset.sum_mul_sq_le_sq_mul_sq
#check @Real.add_pow_le_pow_mul_pow_of_sq_le_sq
#check @ProbabilityTheory.gaussianReal
#check @ProbabilityTheory.IsGaussian
#check @ProbabilityTheory.tendstoInDistribution_inv_sqrt_mul_sum_sub
#check @Matrix.PosDef.eigenvalues_pos
#check @tendsto_integral_of_dominated_convergence
#check @integral_Ioi_of_hasDerivAt_of_tendsto
#check @ConvexOn.map_sum_le
#check @StrictConvexOn.map_sum_lt
#check @InformationTheory.klDiv
#check @Real.exp_sub_one_le
