import json
S = "docs/research/audit-2026-09-24/evidence/plasma-state/"
L = "/home/brian/.local/share/openprover/lean-main/"
findings = []
def F(**k): findings.append(k)

F(id="PS-01", category="faithfulness", severity="high", confidence="CONFIRMED",
  location=L+"CflibsFormal/Continuum.lean:20-40,76-84,125-131 (lineToContRatio, lineToContRatio_strictMono_T); docs/scope-tags.tsv:300",
  claim="The line-to-continuum 'thermometer' has the wrong temperature dependence. The docstring folds the Saha ratio n_z/(n_e*n_ion) into a constant B that it calls 'T-independent to leading order'. By the repo's own Saha law that ratio is 1/S(T), which scales as T^(-3/2)*exp(+chi/kT). Substituting it turns the claimed strictly increasing R_LC = B*sqrt(T)*exp(-a/T) into a strictly DECREASING function of T. The 'load-bearing a >= 0' condition is then an artifact of the reduction.",
  evidence="Continuum.lean:35-37: \"The line-to-continuum coefficient `B` folds the Saha density ratio `n_z/(n_e·n_ion)` and `gA/U`, so it is `T`-independent only to **leading order**\"; :25 \"valid (strictly increasing) thermometer iff `a ≥ 0`\". Saha.lean sahaFactor gives n_{z+1}n_e/n_z = S(T) = 2(U1/U0)(thermalBracket)^{3/2}exp(-chi/kT), so n_z/(n_e n_{z+1}) = 1/S(T), which varies about 49x over 0.8-1.2 eV for chi = 7.9 eV. Script "+S+"lc_ratio.py (chi=7.9, E_k=4, hnu=3 eV, n_e=1e17): the spec form rises 0.146 -> 0.629 while the Saha-substituted form (the repo's own contEmissivity x population, with n_ion = n_z*S/n_e) falls 2.73e-17 -> 1.10e-20 over T = 0.6 -> 1.5 eV. A literature cross-check was retrieved only as a WebSearch summary this session (Bastiaans-Mangold-type formula, primary PDF not read): eps_l/eps_c ∝ A g exp((E_i-ΔE_i)/kT) exp(-E_2/kT) / (U_i λ T_e [ξ(1-e^{-hc/λkT}) + G e^{-hc/λkT}]). That has T_e^{-1}, a positive exponent in (chi - IPD - E_k), and the free-bound term carrying (1-e^{-u}) rather than e^{-u}. It also contradicts the docstring's 'ξ is O(1)' after e^{-u} is pulled out. The CONFIRMED status rests on the in-repo derivation, not on the search result.",
  recommendation="Retag lineToContRatio_strictMono_T as PURE-MATH and delete the thermometer/'leading order' prose, or restate it with the Saha substitution explicit (ratio ∝ exp((chi - ΔE_ipd - E_k)/kT)/(T·U_{z+1}·[ξ(1-e^{-u})+G e^{-u}])) and prove StrictAntiOn under E_k ≤ chi - ΔE. Note that IPD appears in the physical formula. Fix contEmissivity's docstring so it no longer claims e^{-u} times an O(1) ξ for the free-bound part.")

F(id="PS-02", category="docstring_overclaim", severity="high", confidence="CONFIRMED",
  location=L+"CflibsFormal/MatrixIonizationCoupling.lean:59-63 (module header), 285-292 (envelope_ionization_matrix_shift docstring)",
  claim="envelope_ionization_matrix_shift says the n_e shift leaves the homologous-pair subcomposition 'exactly unchanged (matrix effect zero)'. In the statement, clause (c) is a separate conjunct: its densities Ns, Nt are free reals with no link to the fixed points x, y. For element totals read through neutral lines, the module's own sibling definition shows the ratio does move with n_e.",
  evidence="Header :61-63: \"the matrix effect on that ratio is not merely bounded but *zero*\"; docstring :290-291 \"leaves the reported homologous subcomposition ratio exactly unchanged (matrix effect zero ...)\". In the signature, Ns Nt are unconstrained binders; only x,y enter clauses (a),(b). Scratch "+S+"Envelope.lean type-checks (`lake env lean`, OK): `sahaNeutralDensity 1 1 1 / sahaNeutralDensity 2 1 1 ≠ sahaNeutralDensity 1 1 2 / sahaNeutralDensity 2 1 2` (MatrixEffects.lean:240 def). Two elements with S=1,2 have a neutral-density ratio of 1.5 at n_e=1 and 1.333 at n_e=2. MatrixEffects' own docstring (MatrixEffects.lean:~303) says n_e 'enters CF-LIBS only through the Saha ionization balance (stage shuffling), OUTSIDE this module's Boltzmann-only intensity encoding'.",
  recommendation="Rewrite the prose so clause (c) is stated as independent of (a),(b), for fixed emitting-stage densities. Better: instantiate Ns := sahaNeutralDensity S_s Ntot_s x (and y) and prove a two-sided BOUND on the homologous ratio shift in terms of |y - x| and |S_s - S_t|. Zero only when S_s = S_t.")

F(id="PS-03", category="vacuity", severity="high", confidence="CONFIRMED",
  location=L+"CflibsFormal/SahaStability.lean:489-526 (sahaFactorLipConst), PartitionLipschitz.lean:86-176; OuterLoopModelB.outerLoop_contracts; SahaRangeEnclosure.outerLoop_contracts_apriori; docs/frontiers/12-runtime-certificates.md C11",
  claim="sahaFactorLipConst overstates the true T-sensitivity of the Saha factor by 10^6-10^8 on production atomic data. As a result the C11 outer-loop gate L1*L2 < 1 (outerLoop_contracts / _apriori) cannot be met at realistic L2, so the flagship outer-loop contraction certifies nothing in practice. The docstrings say 'deliberately non-sharp' but not by how much.",
  evidence="Script "+S+"lipconst.py re-implements the def at SahaStability.lean:500 verbatim (kB=1, T in eV, S in cm^-3) with levels below IP from CF-LIBS-improved/ASD_da/libs_production.db, and compares it with the true sup|dS/dT| on T in [0.8,1.2] eV. Overestimates: Fe 3.00e7x, Ti 1.03e6x, Al 5.36e7x, Ca 9.69e7x, V 7.71e5x. Causes: (i) the exponential channel's sup exp(-chi/kT) <= 1 is used, where the true value is e^{-7.9/1.2} ≈ 1.4e-3 for Fe; (ii) the ratio sup uses sum g_{z+1} (Fe II: 8208) instead of U_{z+1}(Tmax); (iii) the U-Lipschitz leg uses sum g_k E_k (PartitionLipschitz.lean:86: 'discarding the factor exp(…) ≤ 1'). OuterLoopModelB.lean:46-48 admits the constants are 'deliberately non-sharp' and that 'No concrete end-to-end witness satisfying all hypotheses simultaneously is constructed'. The overhaul's G2 TS-09 reserves C11 for 'L1*L2<1 logged next to converged'.",
  recommendation="Replace the constant with a log-derivative bound (see frontier 'tight Saha Lipschitz': measured 2.8-4.3x of true). In PartitionLipschitz use exp(-E_k/(kB*Tmax)) instead of 1. Until then, the scope notes of OuterLoopModelB/SahaRangeEnclosure and frontiers/12 C11 should say the gate is unsatisfiable on real atomic data.")

F(id="PS-04", category="gap_vs_pipeline", severity="high", confidence="PLAUSIBLE",
  location=L+"CflibsFormal/OuterLoopModelB.lean:14-21, SahaRangeEnclosure.lean:127-137 (legNe := electronDensityFromRatio … T … R with fixed R); SahaEquilibrium.neLeg_mapsTo",
  claim="The spec's outer-loop density leg is n_e(T) = S(T)/R with the stage ratio R held fixed. The pipeline's default sb_offset leg instead derives R from fixed-slope Boltzmann intercepts at the current T. The U1/U0 factor then cancels and a line mean-energy term ΔĒ enters, so ln n_e = ln(SAHA T^1.5) - Δȳ - (χ + ΔĒ)/kT. The Lipschitz theorem therefore bounds a different function from the one the solver iterates, and C11 would not transfer even with a tight constant.",
  evidence="Spec: SahaRangeEnclosure.lean:128 `outerMap (fun T => electronDensityFromRatio kB T me h chi gZ EZ gZ1 EZ1 R) ...` with R a fixed binder; the L1 constant is dominated by U terms (Σg1, Σ gE). Pipeline (overhaul R9-02, 'derived from the code, not yet executed'): 'per element ln n_e = ln(SAHA*T_eV^1.5) - dy_s - (dx_s+IP_s)/T_eV' and 'Partition functions and composition never enter the (T, n_e) update in the sb_offset, Stark and Balmer tiers'. R2-01(C): '∂ln n_e/∂kT ≈ (1.5kT + IP + ΔE_k)/(kT)^2 ≈ 9-10 per eV'. PLAUSIBLE because the pipeline side is the overhaul's code-derivation, not executed.",
  recommendation="Add an intercept-derived density leg, legNe_sb(T) := S(T)/R(T) with R(T) = (U1/U0)(T)*exp(Δȳ + ΔĒ/(kB T)), prove U1/U0 cancels exactly, and state a Lipschitz constant in terms of (χ + ΔĒ). Label the current fixed-R leg as the 'measured stage-population ratio' model and name the pipeline tiers it does and does not cover in OuterLoopModelB's scope note.")

F(id="PS-05", category="gap_vs_pipeline", severity="high", confidence="CONFIRMED",
  location=L+"CflibsFormal/Saha.lean:162-173 (sahaFactor/electronDensityFromRatio: chi a fixed real); SahaStability.electronDensity_relativeError; /home/brian/code/cflibs-formal/docs/integration/m4-population-context.md:30-34",
  claim="IPD is modeled nowhere in the spec. The M4 guidance 'an IPD-lowered χ − Δχ is fine, provided forward and inverse use the same value' is incomplete. Δχ depends on the n_e being solved for (Debye-Hückel ∝ √(n_e/T)), so an IPD-on inverse solves the implicit equation n_e = S(χ − Δχ(n_e))/R. Fixed-χ results such as electronDensity_relativeError (log-derivative exactly −1) and electronDensity_antitone do not transfer: the log-derivative becomes −1/(1−q) with q = Δχ/(2kT). The forward-on/inverse-off bias is exactly the IPD gauge factor.",
  evidence="`rg -i \"debye|IPD|lowering|potential depression\"` over CflibsFormal/ and docs/frontiers/ found no IPD content. The one match, in SahaEquilibrium.lean, was 'Mlip'. Positive control: 'saha' has 21/17 hits in ROADMAP/GAPS. Scratch "+S+"IPDGauge.lean proves (lake env lean, OK) `sahaFactor_ipd_gauge : sahaFactor … (chi - d) … = sahaFactor … chi … * exp(d/(kB*T))` and `ne_ipd_mismatch`: an IPD-off inverse on IPD-on data reports n_e*exp(-d/(kB T)). "+S+"ipd.py, using an electron-only DH anchor at R1-07's 0.0660 eV (1e17 cm^-3, 1e4 K), gives Δχ = 0.0629 eV and exp(-Δχ/kT) = 0.9358 at 1e17/11 kK, which is exactly R1-07's measured 'sb_offset n_e is exactly 0.9358x low'. The anchor also reproduces R1-07's 0.1905 eV at 1e18/12 kK. q = Δχ/2kT is 0.033 at 1e17/11 kK and 0.14-0.16 at the R2-01 runaway states (8.3e18/18.2 kK, 1.2e19/19.3 kK). The inner IPD loop still contracts there, so the runaway is the T-coupling, not IPD. The IPD fold (q = 1) sits at ~9e19 cm^-3 at 11 kK, the edge of the pipeline's [1e12, 1e20] window.",
  recommendation="Add an IPD layer (frontier 'IPD gauge + implicit inverse'): the exact gauge identity (already proved in scratch), the implicit-inverse uniqueness/contraction under q < 1, and the modified log-derivative −1/(1−q). Amend m4-population-context.md §2: 'same χ' must mean the same Δχ(n_e,T) model evaluated at the solved n_e; the fixed-χ theorems apply only with Δχ frozen.")

F(id="PS-06", category="docstring_overclaim", severity="high", confidence="CONFIRMED",
  location=L+"CflibsFormal/SahaStability.lean:52-57, 760-771 (sahaFactor_strictMonoOn_temp hEχ); SahaRangeEnclosure.lean (all three theorems carry hEχ); m4-population-context.md:18",
  claim="The level-ceiling hypothesis hEχ : ∀ k, EZ k ≤ chi is called 'physically universal … true for every real atom'. The tabulated level lists the pipeline uses violate it for most species, so it holds only after a truncation the spec never defines. When IPD lowers χ in the exponent, the obligation becomes EZ ≤ χ − Δχ. That ties the level-cutoff policy to the IPD policy. The DED reference breaks it: IPD-lowered exponent with sharp-IP partition functions, R1-02 corrected evidence. m4-population-context.md does not list hEχ as a transfer condition.",
  evidence="SahaStability.lean:55 'at or below the ionization limit, true for every real atom'; :762 'physically universal hypothesis'. A read-only SQL join of energy_levels with species_physics.ip_ev (libs_production.db) finds 202/324 species with tabulated levels above the IP. Examples: Ca I 342 levels (up to 34.66 eV vs IP 6.113), Na I 318, Mg I 96, Al I 77, Si I 90, Cr I 178, Mn I 192, Cu I 212; Ti/V/Fe ≈ 0. The pipeline masks E < ip (plasma/partition.py:289 `mask = e < ip_ev`) and cuts at ip − s·Δχ on the forward (partition.py:207). R1-02: 'DED reference runs with apply_ipd=True … but its partition functions still use the sharp IP cutoff', and 51 Al I levels lie within 0.1 eV of the IP.",
  recommendation="Reword hEχ as a cutoff obligation: 'the level list is truncated at or below the χ used in the exponent (χ − Δχ when IPD is on)'. Add this as a row-level transfer condition in m4-population-context.md for every theorem carrying hEχ. It is also a formal argument for R1-02's single-PopulationContext cutoff policy: forward and inverse must truncate at the same χ_eff.")

F(id="PS-07", category="gap_vs_pipeline", severity="high", confidence="CONFIRMED",
  location=L+"CflibsFormal/Boltzmann.lean:42-43 (partitionFunction over fixed ι); SahaEquilibrium.jointOuterContraction_box (hLT/hLNe Lipschitz in n_e); frontiers/12 C9-C11",
  claim="The spec's U is a sum over a fixed level set, so it cannot express the pipeline's n_e-dependent Debye-Hückel cutoff U(T, n_e). With a sharp n_e-dependent cutoff, U jumps whenever a level crosses χ − Δχ(n_e), and every n_e-leg built on it is discontinuous. The Lipschitz-in-n_e hypotheses of jointOuterContraction_box and the C9-C11 contraction certificates are then unsatisfiable. Only a continuous cutoff policy (the occupation-probability option named in R1-02) is compatible with the spec's contraction theorems. This is a formal constraint on the cutoff-policy decision R1-02 sends to PAS.",
  evidence="Script "+S+"cutoff_jumps.py (production DB, 11 kK, electron-only DH anchor): as n_e sweeps 1e16 -> 1e18 the number of levels crossing the cutoff is Ca I 178 (U changes 21.0%, largest single jump 0.25%), Na I 87 (37.6%, 1.42%), K I 87 (36.7%, 0.72%), Al I 46 (5.6%), Mg I 89 (7.8%), Ti I 0, Fe I 3. R1-02 lists three live conventions: CPU forward DH, inverse sharp IP, kernel ln-poly. R1-03 records ln-poly errors of 1-12%, and m4-population-context.md:18 already notes that no partitionFunction theorem transfers to a fit or clamp.",
  recommendation="Add a `partitionFunctionCut kB T g E cut` (sum over E k < cut) together with a truncation-error lemma (frontier 'partition truncation'). State explicitly in SahaEquilibrium/OuterLoopModelB that the contraction theorems presuppose U continuous in n_e, which excludes a sharp DH cutoff. Record this in m4-population-context.md as a constraint on R1-02's LevelCutoffPolicy choice.")

F(id="PS-08", category="gap_vs_pipeline", severity="medium", confidence="CONFIRMED",
  location=L+"CflibsFormal/Saha.lean:257-259 (chargeNeutrality_two_stage), SahaEquilibrium.lean multiElementIonized (two stages per element); /home/brian/code/cflibs-formal/docs/spec/03-module-specs.md §1 S1-S9",
  claim="Everything in the plasma-state layer is two-stage. The pipeline must decide the stage-III questions: the II→III edge lowered by 1Δχ in the inverse vs 2Δχ in the forward (R1-07), stage III available only as a polynomial U (R1-03), and stage-III lines that never emit (R1-09). No theorem can settle them. The designed SahaCascade (S1-S9) adds stages but keeps S z a fixed real. Its S9 'EXACT (Saha–Eggert)' binding therefore holds only for an IPD-free, fixed-level-set Saha. With DH lowering the z→z+1 edge shifts by (z+1)Δχ(n_e), and S3's antitonicity in n_e (the crux of uniqueness) needs an additional smallness condition.",
  evidence="`chargeNeutrality` (Saha.lean:178) is general, but the only instantiation is `Fin 2` (`chargeNeutrality_two_stage`, SahaEquilibrium SelfConsistentState). 03-module-specs.md S9: 'with S s z := sahaFactor kB T me h (χ s z) … S5/S6 give the unique LTE charge-neutral n_e at fixed T', tagged 'EXACT (Saha–Eggert)'. With S_z(n_e) = S_z^0·exp((z+1)Δχ(n_e)/kT) and Δχ ∝ √n_e, d ln(S_z/n_e)/d ln n_e = (z+1)Δχ/(2kT) − 1, so stage fractions stay antitone only while (z+1)Δχ/(2kT) < 1. Tagged CONFIRMED on the algebra, not on a Lean proof.",
  recommendation="In the SahaCascade pre-registration, tag S9 'EXACT for IPD-free Saha' and add an S10 for IPD-aware stage factors, with the hypothesis ∀z, (z+1)·Δχ(n_e)/(2kB T) < 1 on the search interval, under which S3/S5/S6 go through. This gives the M4 context a proven rule for the stage-III edge: (z+1)Δχ, i.e. 2Δχ for II→III, as in the forward.")

F(id="PS-09", category="vacuity", severity="medium", confidence="CONFIRMED",
  location=L+"CflibsFormal/StarkBroadening.lean:169-207 (stark_saha_lte_consistent); docs/scope-tags.tsv:275; docs/frontiers/12-runtime-certificates.md:36 (C8); CflibsFormal/Certificates.lean (no C8)",
  claim="The designated Lean guarantee for certificate C8 needs EXACT real equality `hagree` between the Stark and Saha estimates. The C8 predicate in frontiers/12 is a tolerance test |Δn_e|/mean ≤ rtol, so the theorem does not cover the predicate as specified. Its conclusion restates hypotheses (clauses 1-3) plus two trivial inversions, yet it is tagged EXACT (Cristoforetti 2010). Two effects make an exact or tight-tolerance agreement fail on a plasma that is in LTE: an IPD-off Saha inverse disagrees with Stark by exp(Δχ/kT) (6.9% at 1e17/11 kK), and 99.3% of the pipeline's Stark widths are heuristic.",
  evidence="frontiers/12:36: 'C8 … `|Δn_e|/mean ≤ rtol` ∧ `mean ≥ C·√T·ΔE³` | `StarkBroadening.stark_saha_lte_consistent`'. StarkBroadening.lean:192-194 `(hagree : starkDensity w nRef width = electronDensityFromRatio …)`, and its docstring :177-178 says clauses '(1)…(3) … restate the hypotheses'. The Certificates.lean def list (:74-404) has 12 certificates and no C8 or C11. R1-05: 'konjevic_lambda_sq_scaled 50,289; interpolated 16,054; hydrogenic 1,631; stark_b 497 (0.73%)'. G2 TS-09: 'C8 cannot fire in production … _resolve_ne returns on the first successful source'. The IPD factor is from ne_ipd_mismatch (PS-05).",
  recommendation="Retag stark_saha_lte_consistent PURE-MATH (bundling). Implement C8 from a tolerance theorem (frontier 'tolerance-form Stark–Saha bracket'): intersect the Stark bracket (kOpac and w-uncertainty) with the Saha bracket (IPD gauge) and check McWhirter at the lower end. C8 should be restricted to Stark-B or Balmer lines.")

F(id="PS-10", category="generalization", severity="medium", confidence="CONFIRMED",
  location=L+"CflibsFormal/SahaEquilibrium.lean:1390-1640 (jointOuterMap_contraction, jointOuterContraction_box: gate max(a+b)(c+d) < 1 in the unweighted max metric)",
  claim="The 2-D joint (T, n_e) gate is not unit-invariant. The off-diagonal coefficients b = |∂fT/∂n_e| and c = |∂fNe/∂T| change by λ and 1/λ when n_e is rescaled, so the row-sum test can be failed or passed just by choosing units. In the pipeline's natural units (T in eV, n_e in cm^-3), c ≈ n_e·(9-10)/eV ≈ 1e18, so the gate always fails. The invariant condition is the spectral radius of [[a,b],[c,d]] < 1, i.e. a<1, d<1 and bc < (1−a)(1−d). The product bc is invariant under rescaling.",
  evidence="SahaEquilibrium.lean:1394-1395 'Convergence is analysed in the product (max) metric on ℝ × ℝ'; :1421 'contracts by the **row-sum gate** q = max (a+b) (c+d)'. The docstring does call the gate 'sufficient, not necessary' but never mentions scaling. The 1-D gate L1·L2 is invariant (units cancel), so only the 2-D form is affected. Magnitudes: R2-01 '∂ln n_e/∂kT ≈ 9-10 per eV'; lipconst.py true sup|dS/dT| ≈ 2-8e19 cm^-3/eV. A search for 'spectral radius|weighted' found nothing in CflibsFormal/ or frontiers/04.",
  recommendation="Prove the weighted-max-norm version: for weights w_T, w_n > 0 the gate is max(a + b·w_n/w_T, c·w_T/w_n + d) < 1. Add a lemma that suitable weights exist iff a<1 ∧ d<1 ∧ b·c < (1−a)(1−d) (2×2 Perron-Frobenius, elementary). Document that the unweighted gate is unit-dependent.")

F(id="PS-11", category="docs_drift", severity="medium", confidence="CONFIRMED",
  location=L+"CflibsFormal/StarkBroadening.lean:97-110 (mcWhirterBound), PartialLTE.lean:61, Dimensions.lean:183-188; /home/brian/code/cflibs-formal/docs/integration/m4-population-context.md:27-29",
  claim="mcWhirterBound hard-codes a mixed unit convention (n_e in cm^-3, T in K, ΔE in eV), but the docstrings call it 'the dimensionless content' or 'in CGS'. eV is not a CGS unit, and the Dimensions layer cannot represent the bound. The M4 guidance says every identity holds in any consistent unit system, 'e.g. SI with kB in J/K'. In SI, or with T in eV (the pipeline's T_eV convention), lteValid/mcWhirterCert and stark_saha_lte_consistent are wrong by orders of magnitude. stark_saha_lte_consistent also shares one T between sahaFactor (any unit) and lteValid (kelvin only).",
  evidence="StarkBroadening.lean:101-102 'The numerical prefactor and the `√T`, `(ΔE)³` scalings are the dimensionless content of the criterion'; PartialLTE.lean:61 '(`1.6·10¹²` in CGS)'; Dimensions.lean:186-187 'CF-LIBS literature constants (e.g. the McWhirter `1.6e12` …) are quoted in CGS'; m4-population-context.md:28 'e.g. SI with `kB` in J/K, or eV with `kB = 8.617e-5`'. Feeding T in eV instead of K scales √T by 1/√11604 ≈ 1/108, making the LTE gate 108x too lax. Feeding n_e in m^-3 changes it by 1e6.",
  recommendation="State the units in mcWhirterBound's docstring (n_e [cm^-3], T [K], ΔE [eV]), fix the 'CGS' wording, and add an explicit unit caveat to m4-population-context.md for every McWhirter-bearing row (C7, C8, lteValid, stark_saha_lte_consistent, TemporalEvolution.lteWindow).")

F(id="PS-12", category="gap_vs_pipeline", severity="medium", confidence="PLAUSIBLE",
  location=L+"CflibsFormal/SahaEquilibrium.lean:438-1110 (sahaIter, dampedMultiElementIter), SahaContraction.lean; frontiers/12 C9/C10",
  claim="C9/C10 certify a forward closure iteration x = Σ Ntot·S/(x+S) at known element totals Ntot. The default inverse route does not run that iteration: n_e comes from the sb_offset intercept, or from Stark/Balmer, and composition never enters the (T, n_e) update. The certificates therefore attach to the forward Saha solver (saha_boltzmann.py) rather than to the inversion's convergence flag, contrary to the headline 'the CF-LIBS electron-density iteration converges'. Also, given measured absolute neutral densities, neutrality closes in closed form (n_e² = Σ_s n_{I,s}·S_s at fixed T), so no inner iteration is needed on the inverse side.",
  evidence="SahaContraction.lean:73-74 'This is the statement \"the CF-LIBS electron-density iteration converges to the equilibrium n_e\"'. R9-02 (derived, not executed): 'Tiers 1-3 of _update_ne_python (2222-2300) use neither U(T) nor composition'. R2-06: '_update_ne_python returns sb_offset whenever any element shows both stages'. frontiers/12 attaches C10 to 'iterative.py:2022' (the 0.5 damping) in the inverse solver. PLAUSIBLE because the pipeline facts come from overhaul code reading.",
  recommendation="Scope C9/C10 to the forward population solver, and narrow SahaContraction's headline to 'forward Saha-neutrality closure at known totals'. Before claiming the inverse's convergence flag is licensed, check which inverse tier (if any) iterates multiElementIonized.")

F(id="PS-13", category="docstring_overclaim", severity="low", confidence="CONFIRMED",
  location=L+"CflibsFormal/PartialLTE.lean:36-41, 59-64, 114-116",
  claim="thermalizationLimit's docstring treats E* as an ABSOLUTE-energy threshold ('levels at or above E* … thermalize, levels below deviate'), which contradicts the module's own header, where E* is a GAP threshold. The header's justification of the pipeline's E_i ≥ E* cut ('gap ≈ absolute energy, exact only near the ionization limit') has it backwards: near the limit gaps are small while absolute energies are ≈ χ.",
  evidence="PartialLTE.lean:63 '`ΔE ≤ E*`; levels at or above `E*` (near the ionization limit, small gaps) thermalize, levels below'; :36-40 '`ΔE` is the **energy gap** … *not* a level's absolute energy … the collision-limit picture's *approximation* (gap ≈ absolute energy, exact only near the ionization limit where levels pack together)'. At 1e17 cm^-3 and 11 kK, E* = (1e17/(1.6e12·√11000))^{1/3} ≈ 8.4 eV, larger than the Fe/Ti ionization energies, so the absolute-energy cut would discard nothing and the gap reading is the only coherent one.",
  recommendation="Delete the absolute-energy phrasing from thermalizationLimit/thermalizationLimit_antitone_T. If the pipeline cut is to be modelled, express it as a distance from the (IPD-lowered) limit, χ − Δχ − E_i, not E_i itself, and flag the companion's E_i ≥ E* cut as unsupported by this module.")

F(id="PS-14", category="docstring_overclaim", severity="low", confidence="CONFIRMED",
  location=L+"CflibsFormal/SahaInverse.lean:17-19, 86-94 (sahaBoltzmann_plot)",
  claim="The module header and sahaBoltzmann_plot docstring say neutral and ion lines 'lie on a single straight line'. The theorem proves two PARALLEL lines (common slope) whose intercepts are offset by a closed-form shift. The single line of Yalcin / Aguilera-Aragón requires the +χ abscissa shift and the Saha ordinate correction, neither of which appears here.",
  evidence="SahaInverse.lean:87 'BOTH lie on a single straight line of common slope `-1/(k_B T)`', while the conclusion's third clause is `stageIntercept … Nz1 … − stageIntercept … Nz … = log(Nz1/Nz) + (log U_z − log U_{z+1})` (a nonzero offset). The citation-whitelist entry for Aguilera & Aragón 2007 (docs/citation-whitelist.tsv:48) records that the audit 'confirmed the +χ abscissa shift and Saha-bracket ordina[te]'.",
  recommendation="Reword to 'two parallel lines with a Saha-determined intercept offset'. Point to the Alt.CSigma single-line results (csigma_saha_master_line/universal_line) for the collapsed form. Tag remains REDUCED.")

F(id="PS-15", category="scope_tag", severity="low", confidence="CONFIRMED",
  location=L+"CflibsFormal/SpatialForward.lean (whole module); docs/scope-tags.tsv:221-222",
  claim="The onion-peeling forward map I = L·ε assumes OPTICALLY THIN chords (additive emissivity with no attenuation along the chord), but the module never says so, and chord_profile_identifiable / singleZone_identifiable are tagged EXACT. The overhaul estimates τ0 ≈ 4 for Al I 396.15 at L = 1 mm, which makes the linear model inapplicable to resonance lines.",
  evidence="`rg -n -i \"optically|thin|absorption|opacity\" SpatialForward.lean` returns only :109 'Kept as a thin wrapper' (the positive control shows the pattern ran). scope-tags.tsv:221 'chord_profile_identifiable EXACT Parigger 2016'. Overhaul R1-04: 'tau0 ≈ 4 for L = 1 mm'.",
  recommendation="Add an 'optically thin along every chord' scope line and retag the two identifiability results REDUCED, or keep EXACT for the matrix statement (PURE-MATH) and move the physics claim to prose.")

F(id="PS-16", category="gap_vs_literature", severity="low", confidence="CONFIRMED",
  location=L+"CflibsFormal/NonLTEKinetics.lean:1-95; StarkBroadening.lean:81-95; HydrogenStark.lean",
  claim="Two parts of the non-equilibrium and diagnostic layer are missing. (i) NonLTEKinetics models only EXCITATION departures b_k inside one stage, in an ionizing two-level balance (b ≤ 1). It has no ionization-balance (Saha) departure, which is the channel that biases every Saha-derived n_e and is what TS-02 finds the McWhirter-based flag cannot see. (ii) The Stark n_e diagnostics treat w, n_ref and the T-scaling (T/1e4)^α as exact. There is no δw → δn_e transfer lemma, although the pipeline's widths are 99.3% heuristic and the overhaul proposes a [1/3, 3] scale band.",
  evidence="NonLTEKinetics.lean:27-33 departureCoeffNe with sandwich '0 ≤ b₂ ≤ 1 (radiative leakage only *underpopulates* the upper level)', and no Saha/ionization departure definition (the only ionization content is in Saha.lean). StarkBroadening.lean:86-95 starkFWHM/starkDensity with w exact; StarkOpacityGuard brackets only the width (kOpac), not w. R1-05 Stark source counts; R2-06: 'the Stark inversion depends only weakly on T through (T/1e4)^α'.",
  recommendation="Add (a) a Saha departure coefficient b_Z with n_{z+1}n_e/n_z = b_Z·S(T), and the exact statement that a Saha-derived n_e is off by exactly b_Z; (b) a Stark w-bracket lemma starkDensity w_hi ≤ n_e ≤ starkDensity w_lo (a one-line sibling of starkDensity_brackets_true), and feed both into the C8 tolerance theorem.")

frontier = []
def FI(**k): frontier.append(k)

FI(title="IPD gauge and the implicit IPD-aware Saha inverse",
   informal_statement="(a) Gauge: lowering χ by Δχ multiplies S by exp(Δχ/kT). An IPD-off inverse applied to IPD-on data therefore reports n_e·exp(−Δχ/kT), and for the I→II balance with an element-independent Δχ, line-ratio-only inverses (sb_offset) identify only n_e·e^{−Δχ/kT}. Composition from such routes is IPD-invariant, which explains R1-07's 'composition unchanged, n_e 0.936x'. (b) With Δχ = c·√(n_e/T), the inverse is the fixed point n = a·exp(c√n/(√T·kT)). In log coordinates the map has derivative q = Δχ/(2kT), so the root is unique and Picard converges at rate q wherever q < 1; roots merge (fold) at q = 1. (c) d ln n_e/d ln R = −1/(1−q). (d) A Stark n_e (IPD-agnostic) and an IPD-off Saha n_e differ by exactly e^{Δχ/kT}, so a Stark/Saha pair measures Δχ.",
   lean_sketch="theorem sahaFactor_ipd_gauge : sahaFactor kB T me h (chi - d) gZ EZ gZ1 EZ1 = sahaFactor kB T me h chi gZ EZ gZ1 EZ1 * Real.exp (d/(kB*T))  -- PROVED in scratch IPDGauge.lean\ntheorem ne_ipd_mismatch (hR : R ≠ 0) (hfwd : R*ne = sahaFactor … (chi - d) …) : electronDensityFromRatio … chi … R = ne * Real.exp (-(d/(kB*T)))  -- PROVED in scratch\ndef ipdInverseMap (a b : ℝ) (ℓ : ℝ) : ℝ := Real.log a + b * Real.exp (ℓ/2)   -- ℓ = log n_e, b·e^{ℓ/2}=Δχ/kT\ntheorem ipdInverse_contracts (hq : ∀ ℓ ∈ Set.Icc ℓ0 ℓ1, b*Real.exp (ℓ/2)/2 ≤ q) (hq1 : q < 1) (hmaps : MapsTo …) : ∃! ℓ ∈ Icc ℓ0 ℓ1, ipdInverseMap a b ℓ = ℓ ∧ Tendsto … (via outerContraction_box-style ContractingWith)",
   why_it_matters="Turns the overhaul's measured 0.9358x n_e bias (R1-07, bead 3n4a) into a theorem. It gives M4 a proven rule for the apply_ipd default: composition is invariant on line-ratio routes, while Stark/injected n_e routes are biased by exactly e^{Δχ/kT}. It also certifies the jitpipe 3-step inner IPD loop (error ≤ q³ ≈ 3e-5 at 1e17) and locates the fold (q=1, ~9e19 cm^-3 at 11 kK) where uniqueness fails.",
   pipeline_link="R1-07 (IPD forward-on/inverse-off, 0.936x), bead 3n4a, R2-01(C) IPD positive feedback, R9-02 (jitpipe 3 inner IPD steps), BL for apply_ipd default; M4 PopulationContext IPD enum; C3 NeutralityScale (Stark n_e + IPD-off Saha biases Fcal by e^{-Δχ/kT})",
   literature="Overhaul R1-07 (electron-only vs electron+ion Debye-Hückel; Stewart–Pyatt low-density limit named there). No new citation is needed for (a),(c),(d), which are algebra on Saha–Eggert (Griem 1997, whitelisted). The Δχ ∝ √(n_e/T) form is Debye–Hückel; cite it only through R1-07 or a vetted source.",
   mathlib_prereqs="Real.exp_add, Real.exp_neg, Real.exp_le_exp (Analysis/Complex/Exponential.lean:317), ContractingWith.exists_fixedPoint' (Topology/MetricSpace/Contracting.lean:152), Convex.norm_image_sub_le_of_norm_deriv_le (Analysis/Calculus/MeanValue.lean:729), Real.add_one_le_exp (Exponential.lean:633)",
   repo_anchors="Saha.lean:sahaFactor, electronDensityFromRatio, log_sahaFactor, saha_relation; SahaStability.lean:electronDensity_relativeError; SahaEquilibrium.lean:outerContraction_box; StarkBroadening.lean:starkDensity; Alt/NeutralityScale.lean:neutralityScale_eq_Fcal",
   already_exists_check="rg -i 'debye|IPD|lowering|potential depression' over CflibsFormal/ and docs/frontiers/: no IPD content (the only match in SahaEquilibrium.lean was the substring in 'Mlip'). Positive control: rg -c -i saha on ROADMAP/GAPS gives 21/17. IPD appears only in docs/2dcos (monograph prose, Stewart–Pyatt citation), with no Lean. Scratch proofs of (a) are at docs/research/audit-2026-09-24/evidence/plasma-state/IPDGauge.lean (lake env lean OK).",
   tractability="A",
   risks="(b) needs a derivative/MVT argument or a derivative-free exp convexity bound. The choice of Δχ model (electron-only 4π vs electron+ion 8π, per R1-07) is an owner decision; keep c abstract. The gauge invariance of composition fails once charge neutrality fixes absolute n_e, or once stage III (2Δχ edge) is present. State both limits.")

FI(title="Tight log-derivative T-Lipschitz constant for the Saha factor (makes C11 fireable)",
   informal_statement="Under hEχ (levels truncated at χ) with E ≥ 0, d ln S/dT = 3/(2T) + (χ − ⟨E⟩₀(T))/(kT²) + ⟨E⟩₁(T)/(kT²) ∈ (0, 3/(2T) + (χ + ⟨E⟩₁(Tmax))/(kT²)]. The mean level energy ⟨E⟩(T) is nondecreasing in T (a variance argument), and S is increasing (sahaFactor_strictMonoOn_temp). Hence on [Tmin,Tmax], |S(T1) − S(T2)| ≤ S(Tmax)·(3/(2Tmin) + (χ + ⟨E⟩₁(Tmax))/(kB·Tmin²))·|T1 − T2|.",
   lean_sketch="noncomputable def meanLevelEnergy (kB T) (g E : ι → ℝ) : ℝ := (∑ k, g k * E k * boltzmannFactor kB T (E k)) / partitionFunction kB T g E\ntheorem meanLevelEnergy_mono_temp (hg) (hE : ∀ k, 0 ≤ E k) : MonotoneOn (fun T => meanLevelEnergy kB T g E) (Set.Ioi 0)\ntheorem sahaFactor_lipschitz_temp_tight … (hEχ : ∀ k, EZ k ≤ chi) (hT1 hT2 : _ ∈ Icc Tmin Tmax) : |sahaFactor … T1 … - sahaFactor … T2 …| ≤ sahaFactor … Tmax … * (3/(2*Tmin) + (chi + meanLevelEnergy kB Tmax gZ1 EZ1)/(kB*Tmin^2)) * |T1 - T2|",
   why_it_matters="The current sahaFactorLipConst is 7.7e5-9.7e7x above the true sup|dS/dT| on production data, so C11 can never pass (PS-03). The candidate bound measures 2.76-4.34x of the true value (Fe 2.83, Ti 2.88, Al 3.02, Ca 4.34, V 2.76; lipconst.py). That turns C11 into a gate that can fire. The same trick fixes PartitionLipschitz: use exp(−E/(kB·Tmax)) instead of 1.",
   pipeline_link="G2 TS-09 (C11 reserved; log L1·L2 next to converged); R9-02 (damped Picard ρ = ½(1+cβ)); frontiers/12 C11; BL-35 root/contraction certificate",
   literature="Saha–Eggert (Griem 1997, whitelisted); pure real analysis otherwise.",
   mathlib_prereqs="Convex.norm_image_sub_le_of_norm_deriv_le (Analysis/Calculus/MeanValue.lean:729) or exists_deriv_eq_slope (Analysis/Calculus/Deriv/MeanValue.lean:152); HasDerivAt.sum / HasDerivAt.exp; Real.log_le_log; Finset.inner_mul_le_norm_mul_norm or a direct Cauchy–Schwarz for the variance ≥ 0 step",
   repo_anchors="SahaStability.lean:sahaFactorLipConst, sahaFactor_lipschitz_temp, sahaFactor_strictMonoOn_temp, partitionFunction_upper_growth, partitionFunction_mono_temp; PartitionLipschitz.lean:partitionFunction_two_point_bound; OuterLoopModelB.outerLoop_contracts; SahaRangeEnclosure.outerLoop_contracts_apriori",
   already_exists_check="rg -i 'meanEnergy|mean energy|averageEnergy' CflibsFormal/ matches only line-set mean energies (ErrorBudget:503, FisherLineSelection:33), not a Boltzmann-weighted level mean. sahaFactorLipConst (SahaStability.lean:500) is the only T-Lipschitz constant, and it uses Σg and exp ≤ 1.",
   tractability="B",
   risks="Needs derivatives of finite sums of exp in T (or a derivative-free two-point version via log-convexity of U in β). Using max E₁ instead of ⟨E⟩₁(Tmax) is easier and still 5.8-9.8x tight. It must be combined with PS-04: the pipeline's sb_offset leg has U cancelled and a ΔĒ term, so its constant is S(Tmax)·(3/(2Tmin) + (χ+ΔĒ)/(kTmin²)).")

FI(title="Partition-function truncation: error bound, T-dependence of the cutoff bias, and same-list cancellation",
   informal_statement="For level lists ι ⊆ ι′ where every added level lies at or above the cutoff E_c ≥ max_ι E: (i) 0 ≤ U′ − U ≤ (Σ_{added} g)·exp(−E_c/kT); (ii) the ratio U′/U is nondecreasing in T, and strictly increasing if some added level lies strictly above some retained level. So the Saha n_e, ionization fractions and classic densities computed under two cutoff policies differ by a factor that genuinely depends on T, and no T-independent multiplicative correction (such as the calibration layer's gA factors) can absorb it. (iii) population and boltzmann_plot are invariant under truncation only if the numerator and U use the same list (conventions.md §2 prose, as a theorem).",
   lean_sketch="noncomputable def partitionFunctionCut (kB T cut) (g E : ι → ℝ) : ℝ := ∑ k ∈ univ.filter (fun k => E k < cut), g k * boltzmannFactor kB T (E k)\ntheorem partitionFunction_sub_cut_le (hg) (hkT : 0 < kB*T) : partitionFunction kB T g E - partitionFunctionCut kB T cut g E ≤ (∑ k ∈ univ.filter (fun k => cut ≤ E k), g k) * Real.exp (-cut/(kB*T))\ntheorem cutRatio_monotoneOn_temp (hg) (hcut : ∀ j k, E j < cut → cut ≤ E k → E j ≤ E k) : MonotoneOn (fun T => partitionFunction kB T g E / partitionFunctionCut kB T cut g E) (Set.Ioi 0)\ntheorem cutRatio_not_const … : ∃ T1 T2, ratio T1 ≠ ratio T2  -- non-absorbability by a T-independent factor",
   why_it_matters="This is the formal content behind R1-02, the critical overhaul finding: three live cutoff conventions, U ratios up to 2.4x, a 'T-dependent ~5% Al I bias' that 'T-independent gA corrections cannot absorb'. It supplies the δ_U(T) that AtomicDataPerturbation's δ_U slot consumes and the error term PS-07 needs, and it gives M4's LevelCutoffPolicy a proven comparison between policies.",
   pipeline_link="R1-02 (critical, cutoff conventions), R1-03 (ln-poly retirement), R1-10 (fit-window clamps), M4 PopulationContext LevelCutoffPolicy; owner rule that calibration-layer gA corrections are T-independent",
   literature="Pure algebra on the Boltzmann partition sum (Griem 1997 for U). R1-02 names the Hummer & Mihalas 1988 occupation-probability alternative. That name is cited from R1-02 only and has not been verified here.",
   mathlib_prereqs="Finset.sum_filter_add_sum_filter_not, Finset.sum_le_sum_of_subset_of_nonneg, Finset.sum_le_sum, Real.exp_le_exp (Exponential.lean:317), div_le_div_iff₀",
   repo_anchors="Boltzmann.lean:partitionFunction, population, boltzmann_plot; AtomicDataPerturbation.lean δ_U slot (classicDensity_aliasing_error_channels, :41-42,:229); docs/conventions.md:69-76 (level set = line set idealization)",
   already_exists_check="rg -i 'trunc|tail|cutoff' over Boltzmann.lean, PartitionLipschitz.lean, ForwardMap.lean and AtomicDataPerturbation.lean: 0 hits (positive control: 'partitionFunction' has 9 hits in Boltzmann.lean). conventions.md:74 states the under-estimate in prose only. AtomicDataPerturbation has a generic same-T |U'−U| ≤ δ_U·U slot, with no cutoff structure and no T-dependence.",
   tractability="A",
   risks="The monotone-ratio lemma needs the 'added levels above retained levels' hypothesis, which fails for the sharp-IP vs DH comparison only if the level ordering is interleaved (it is not). For an occupation-probability policy (continuous weights) the statement must be generalized to weights w_k(n_e) ∈ [0,1].")

FI(title="Unit-invariant 2×2 gate for the joint (T, n_e) outer map",
   informal_statement="For nonnegative coefficients a, b, c, d, the following are equivalent: there exist weights w_T, w_n > 0 such that the joint map contracts in the weighted max metric max(|ΔT|/w_T, |Δn|/w_n); and a < 1 ∧ d < 1 ∧ b·c < (1−a)(1−d), i.e. spectral radius < 1. The condition is invariant under rescaling n_e (b → b/λ, c → λc), unlike the current row-sum gate max(a+b, c+d) < 1.",
   lean_sketch="theorem exists_weights_iff (ha hb hc hd : 0 ≤ _) : (∃ wT wn, 0 < wT ∧ 0 < wn ∧ max (a + b*wn/wT) (c*wT/wn + d) < 1) ↔ (a < 1 ∧ d < 1 ∧ b*c < (1-a)*(1-d))\ntheorem jointOuterContraction_box_weighted … (hgate : a < 1 ∧ d < 1 ∧ b*c < (1-a)*(1-d)) : ∃! pstar ∈ box, jointOuterMap fT fNe pstar = pstar ∧ Tendsto … -- apply jointOuterContraction_box to the rescaled coordinates (T/wT, n/wn)",
   why_it_matters="With T in eV and n_e in cm^-3 the existing gate always fails (c ≈ 1e18), so the 2-D certificate is unit-dependent and in practice unusable. The invariant form is necessary and sufficient for the linearized Lipschitz matrix. It gives the coupled Aguilera–Aragón T–n_e loop (R9-02 Picard, R9-03 Anderson) a runtime check that does not depend on units.",
   pipeline_link="G2 TS-09 / frontiers/12 C11 (2-D jointOuterMap_contraction named as the analogous glue); R9-02/R9-03 (T–n_e fixed point, damping), R2-01(C)",
   literature="Elementary linear algebra (2×2 Perron–Frobenius / M-matrix criterion); no domain citation needed.",
   mathlib_prereqs="ContractingWith.exists_fixedPoint' (Topology/MetricSpace/Contracting.lean:152), Prod.dist_eq, isClosed_Icc.prod; the weight existence is nlinarith/polyrith algebra (choose wn/wT = (1−a)/b adjusted, or the Perron vector)",
   repo_anchors="SahaEquilibrium.lean:jointOuterMap, jointOuterMap_contraction (:1426), jointOuterContraction_box (:1585), outerContraction_box (1-D, already unit-invariant)",
   already_exists_check="rg -i 'spectral.radius|weighted max|weighted.*metric|rescal' CflibsFormal/ docs/frontiers/04-outer-t-iteration.md: no joint-map hits (only unrelated EquivalentWidth/Classic rescaling identities).",
   tractability="A",
   risks="The equivalence is for the Lipschitz-coefficient matrix, i.e. a sufficient condition for the nonlinear map. The weights must be fixed before the run, so the certificate reports the chosen weights. Degenerate b = 0 or c = 0 cases need a separate branch.")

FI(title="Tolerance-form Stark–Saha LTE certificate (C8 with a real guarantee)",
   informal_statement="Let the Stark route give a bracket n_e ∈ [n_S/(kOpac·ρ_w), n_S·ρ_w] (opacity budget kOpac ≥ 1 from StarkOpacityGuard, width-parameter uncertainty ρ_w ≥ 1). Let the Saha route give n_e ∈ [n_Saha·e^{−Δχmax/kT}, n_Saha·e^{Δχmax/kT}] (IPD gauge band, if IPD is unresolved) widened by electronDensity_lipschitz for a ratio error. If the two brackets intersect, the true n_e lies in the intersection. If McWhirter holds at the intersection's lower end, then McWhirter holds at the true n_e. If the brackets are disjoint, the LTE + model hypotheses are refuted.",
   lean_sketch="def starkSahaTolCert (C T dE nS nSaha kOpac ρw κ : ℝ) : Prop := max (nS/(kOpac*ρw)) (nSaha/κ) ≤ min (nS*ρw) (nSaha*κ) ∧ C*√T*dE^3 ≤ max (nS/(kOpac*ρw)) (nSaha/κ)\ntheorem starkSahaTolCert_sound (hStark : nS/(kOpac*ρw) ≤ neTrue ∧ neTrue ≤ nS*ρw) (hSaha : nSaha/κ ≤ neTrue ∧ neTrue ≤ nSaha*κ) (h : starkSahaTolCert …) : mcWhirterCert C T dE neTrue\ntheorem starkSaha_disjoint_refutes (hdisj : nS*ρw < nSaha/κ) : ¬ (hStark ∧ hSaha)",
   why_it_matters="C8 is 'grade A, implement now' in frontiers/12, but its guarantee theorem needs exact equality and the certificate is absent from Certificates.lean (PS-09). This version fills C8 soundly, applies the R3 refusal (two independent diagnostics), and makes the disjoint case a proven refutation. That gives an informative LTE flag, where TS-02 finds the current C7-style flag anti-informative on supercam_labcal.",
   pipeline_link="G2 TS-09 (C8 reserved; _resolve_ne must record all sources), TS-01 (single-diagnostic circularity), TS-02; R1-05 (heuristic Stark widths → ρ_w), R2-06 (Stark overridden by sb_offset); frontiers/12 C8, R3",
   literature="McWhirter 1965 and Cristoforetti 2010 (whitelisted) for the bound; Griem 1974 (whitelisted) for the linear width; the IPD band as in the IPD frontier.",
   mathlib_prereqs="le_trans, div_le_iff₀, mul_le_mul_of_nonneg_left, Real.sqrt_nonneg, pow_le_pow_left₀; no analysis needed",
   repo_anchors="StarkBroadening.lean:starkDensity, lteValid, stark_saha_lte_consistent; StarkOpacityGuard.lean:starkDensity_brackets_true (:128-133), starkOpacity_certificate_sound; SahaStability.lean:electronDensity_lipschitz; Certificates.lean:mcWhirterCert (:239)",
   already_exists_check="rg -n 'rtol|starkDensity .* ≤' CflibsFormal/: only StarkOpacityGuard's one-sided/bracket lemmas (:86-133) on the Stark side. There is no Saha-side bracket, no intersection certificate, and no C8 def in Certificates.lean (def list :74-404 has 12 certificates).",
   tractability="A",
   risks="ρ_w and kOpac are assumed inputs (a C14-style refusal note is needed). The McWhirter prefactor units must be fixed first (PS-11). The pipeline must actually compute two diagnostics in one solve (TS-09 says it does not).")

FI(title="Saha–Boltzmann consistency is non-informative on the sb_offset route (refusal theorem)",
   informal_statement="If n_e is defined from the observed inter-stage intercept offset, n̂_e := S(T)/R̂(T) with R̂ built from the same intercepts, then the Saha-consistency residual R̂(T)·n̂_e − S(T) is identically 0 for every data set. The Saha temperature solving S(T_saha)/n̂_e = R̂(T_saha) equals T_fit whenever S/R̂ is injective in T. So the consistency statistic is a constant function of the data and carries zero information.",
   lean_sketch="theorem sahaConsistency_trivial_of_sbOffset (hR : Rhat ≠ 0) : Rhat * electronDensityFromRatio kB T me h chi gZ EZ gZ1 EZ1 Rhat = sahaFactor kB T me h chi gZ EZ gZ1 EZ1  -- (saha_relation hR).mp rfl\ntheorem sahaTemperature_eq_fit (hinj : Set.InjOn (fun T => sahaFactor … T … / Rhat T) box) (hTfit ∈ box) (hTsaha ∈ box) (hsol : sahaFactor … Tsaha … / Rhat Tsaha = electronDensityFromRatio … Tfit … (Rhat Tfit)) : Tsaha = Tfit",
   why_it_matters="Formalizes overhaul TS-01, a critical finding: the pipeline's LTE consistency criterion scores 'excellent' by construction on the default route. Frontiers/12 R3 states this only in prose. A theorem lets validity.py mark the criterion not_evaluated on the sb_offset route with a cited reason.",
   pipeline_link="G2 TS-01 (critical), TS-02, TS-04; frontiers/12 §5 R3; C1 abstention bake-off",
   literature="None needed (algebra on Saha–Eggert, Griem 1997).",
   mathlib_prereqs="Set.InjOn, eq_div_iff; nothing beyond saha_relation",
   repo_anchors="Saha.lean:saha_relation, electronDensity_antitone; SahaStability.lean:electronDensityFromRatio_strictMonoOn_temp (supplies injectivity under hEχ); SahaInverse.lean:sahaBoltzmann_shift_eq_log_saha",
   already_exists_check="rg -i 'circular|tautolog' CflibsFormal/ finds only non-circularity disclaimers for other constructions (VoigtErrorEnclosure, Inverse, SpatialForward, MatrixIonizationCoupling, DoubletChannel). There is no statement that a diagnostic is non-informative. Frontiers/12 R3 is prose only.",
   tractability="A",
   risks="Mathematically trivial. Its value is as a refusal theorem that the companion can cite. Map the pipeline's weighted vs unweighted intercepts (TS-01 (i)) and the raw vs IPD-lowered IP (TS-01 (ii)) explicitly, or the trivial identity will be over-read as covering those mismatches too.")

summary = ("Slice: plasma-state physics (20 modules). I audited statements in full for Boltzmann, Saha, SahaStability, SahaEquilibrium (single/multi-element core plus the 1-D/2-D outer spines), SahaContraction, SahaRangeEnclosure, SahaInverse, PartialLTE, Continuum, Dimensions, MatrixIonizationCoupling, StarkBroadening and HydrogenStark. I audited headers and scope tags only for NonLTEKinetics, TemporalEvolution, SpatialForward, StarkShift, StarkOpacityGuard, DoubletChannel and PartitionLipschitz. "
 "The core constants are right: g_e = 2, (2π m_e kT/h²)^{3/2} via rpow, exp(−χ/kT), McWhirter's √T·ΔE³ direction, Stark linear/2-3 exponents. Most modules are carefully scoped (TemporalEvolution, StarkOpacityGuard, DoubletChannel are exemplary). "
 "Two statements are physically wrong or overclaimed. Continuum's line-to-continuum 'thermometer' gets the wrong T-direction once the repo's own Saha law is substituted. The MatrixIonizationCoupling envelope claims a 'zero matrix effect' that its own sahaNeutralDensity refutes (checked in Lean). "
 "The quantitative outer-loop machinery is vacuous in practice: sahaFactorLipConst is 10^6-10^8x loose on production atomic data, so the C11 gate cannot fire. Its density leg, n_e = S(T)/R with R fixed, is not the leg the pipeline's sb_offset tier iterates. "
 "Against the overhaul: IPD is absent from the spec. The IPD gauge identity, now proved in scratch, reproduces R1-07's 0.9358x n_e bias exactly. The level-ceiling hypothesis hEχ ('true for every real atom') fails on the raw DB for 202/324 species and couples the cutoff to the IPD policy. A sharp n_e-dependent (Debye–Hückel) cutoff makes U discontinuous in n_e (Ca I: 178 levels cross between 1e16 and 1e18), which excludes every Lipschitz/contraction theorem. Stage III and the 1Δχ-vs-2Δχ edge are unmodelled, and the SahaCascade design (S1-S9) keeps S fixed. "
 "C8's guarantee needs exact equality, and C8 cannot pass on real data given the IPD-off inverse and heuristic Stark widths. "
 "Six frontier ideas follow. The IPD gauge and implicit inverse, partition truncation, the unit-invariant 2-D gate and the tolerance C8 are tractability A; the tight Saha Lipschitz constant (measured 2.8-4.3x of true) is tractability B. "
 "Evidence scripts are in docs/research/audit-2026-09-24/evidence/plasma-state/.")

out = dict(summary=summary, findings=findings, frontier_ideas=frontier)
json.dump(out, open(S+"output.json","w"), indent=1, ensure_ascii=False)
print(len(findings), len(frontier), len(json.dumps(out)))
