#!/usr/bin/env python3
"""Regression-check a CF-LIBS implementation against the verified-spec fixtures.

`oracle/fixtures.json` is generated by the Float mirror of the verified CflibsFormal Lean
spec (`oracle/Generate.lean`); each check instantiates a PROVEN theorem (see oracle/README.md).

This script ships a REFERENCE implementation of the formulas (matching the spec), so running
it self-checks the fixtures. To regression-test YOUR pipeline (CF-LIBS-improved), replace the
functions in the IMPL block with calls into your code and re-run:

    python3 oracle/check_fixtures.py

Exit 0 if all checks pass, 1 otherwise. Pure stdlib (no numpy).
"""
from __future__ import annotations
import json
import math
import os
import sys

RTOL = 1e-6  # formula-correctness tolerance; real bugs differ by >> this.

# ======================= IMPL — the formulas under test ============================
# Replace these with calls into CF-LIBS-improved to regression-test your pipeline.
# They mirror the verified CflibsFormal definitions (Boltzmann.lean, ForwardMap.lean,
# Classic.lean, Closure.lean) exactly.

def boltzmann_factor(kB, T, E):
    return math.exp(-E / (kB * T))

def partition_function(kB, T, g, E):
    return sum(gk * boltzmann_factor(kB, T, Ek) for gk, Ek in zip(g, E))

def population(kB, T, N, g, E, k):
    return N * g[k] * boltzmann_factor(kB, T, E[k]) / partition_function(kB, T, g, E)

def line_intensity(kB, T, N, Fcal, g, E, A, k):
    return Fcal * A[k] * population(kB, T, N, g, E, k)

def classic_density(kB, T, Fcal, g, E, A, u, I):
    return I * partition_function(kB, T, g, E) / (Fcal * A[u] * g[u] * boltzmann_factor(kB, T, E[u]))

def composition(n, s):
    return n[s] / sum(n)
# ===================================================================================


def approx(a, b, rtol=RTOL):
    return abs(a - b) <= rtol * max(1.0, abs(b))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "fixtures.json")) as f:
        fx = json.load(f)
    c = fx["constants"]
    kB, T, Fcal = c["kB"], c["T"], c["Fcal"]
    g, E, A = c["g"], c["E"], c["A"]
    species = fx["species"]
    checks = fx["checks"]
    fails = []

    def check(name, cond, detail=""):
        print(f"  [{'PASS' if cond else 'FAIL'}] {name}" + ((" — " + detail) if (detail and not cond) else ""))
        if not cond:
            fails.append(name)

    print(f"forward  ({checks['forward']['theorem']})")
    for i, s in enumerate(species):
        for k, expected in enumerate(s["intensities"]):
            got = line_intensity(kB, T, s["N"], Fcal, g, E, A, k)
            check(f"species[{i}].intensity[{k}]", approx(got, expected), f"got {got} vs {expected}")

    print(f"round_trip  ({checks['round_trip']['theorem']})")
    rt = checks["round_trip"]
    for i, s in enumerate(species):
        u = s["u"]
        I = line_intensity(kB, T, s["N"], Fcal, g, E, A, u)
        rec = classic_density(kB, T, Fcal, g, E, A, u, I)
        check(f"recover species[{i}].N", approx(rec, s["N"]), f"got {rec} vs {s['N']}")
        check(f"fixture recovered[{i}] == true", approx(rt["recovered_densities"][i], rt["true_densities"][i]))

    print(f"closure  ({checks['closure']['theorem']})")
    cl = checks["closure"]
    dens = [classic_density(kB, T, Fcal, g, E, A, s["u"],
                            line_intensity(kB, T, s["N"], Fcal, g, E, A, s["u"])) for s in species]
    comp = [composition(dens, i) for i in range(len(dens))]
    for i in range(len(comp)):
        check(f"composition[{i}] == true", approx(comp[i], cl["true_composition"][i]),
              f"got {comp[i]} vs {cl['true_composition'][i]}")
    check("sum(composition) == 1", approx(sum(comp), 1.0), f"sum = {sum(comp)}")

    print(f"calibration_free  ({checks['calibration_free']['theorem']})")
    cf = checks["calibration_free"]
    scale = cf["Fcal_scale"]

    def comp_with(fc):
        d = [classic_density(kB, T, fc, g, E, A, s["u"],
                             line_intensity(kB, T, s["N"], fc, g, E, A, s["u"])) for s in species]
        return [composition(d, i) for i in range(len(d))]

    base, scaled = comp_with(Fcal), comp_with(Fcal * scale)
    for i in range(len(base)):
        check(f"composition invariant under Fcal x{scale:g} [{i}]", approx(base[i], scaled[i]),
              f"{base[i]} vs {scaled[i]}")
        check(f"matches fixture composition_base[{i}]", approx(base[i], cf["composition_base"][i]))

    print()
    if fails:
        print(f"FAILED: {len(fails)} check(s): {', '.join(fails)}")
        sys.exit(1)
    print("ALL CHECKS PASSED — implementation matches the verified-spec fixtures.")
    sys.exit(0)


if __name__ == "__main__":
    main()
