#!/usr/bin/env python3
"""Regression-check a CF-LIBS implementation against the verified-spec fixtures.

`oracle/fixtures.json` is generated by the Float mirror of the verified CflibsFormal Lean
spec (`oracle/Generate.lean`); each check instantiates a PROVEN theorem (see oracle/README.md).
Two scenarios: a multi-element ternary alloy (classic + OLS + self-absorbed estimators,
per-element temperature) and a two-stage Saha-Boltzmann element (recover T and n_e).

This script ships a REFERENCE implementation of the formulas (matching the spec), so running
it self-checks the fixtures. To regression-test YOUR pipeline (CF-LIBS-improved), replace the
functions in the IMPL block with calls into your code and re-run:

    python3 oracle/check_fixtures.py

Exit 0 if all checks pass, 1 otherwise. Pure stdlib (no numpy).
"""
from __future__ import annotations
import json
import math
import os
import sys

RTOL = 1e-6  # formula-correctness tolerance; real bugs differ by >> this.

# ======================= IMPL — the formulas under test ============================
# Replace these with calls into CF-LIBS-improved to regression-test your pipeline.
# They mirror the verified CflibsFormal definitions exactly.

def boltzmann_factor(kB, T, E):
    return math.exp(-E / (kB * T))

def partition_function(kB, T, g, E):
    return sum(gk * boltzmann_factor(kB, T, Ek) for gk, Ek in zip(g, E))

def population(kB, T, N, g, E, k):
    return N * g[k] * boltzmann_factor(kB, T, E[k]) / partition_function(kB, T, g, E)

def line_intensity(kB, T, N, Fcal, g, E, A, k):
    return Fcal * A[k] * population(kB, T, N, g, E, k)

def classic_density(kB, T, Fcal, g, E, A, u, I):
    return I * partition_function(kB, T, g, E) / (Fcal * A[u] * g[u] * boltzmann_factor(kB, T, E[u]))

def composition(n, s):
    return n[s] / sum(n)

def recover_T(kB, g, E, A, i, j, Ii, Ij):
    yi = math.log(Ii / (g[i] * A[i]))
    yj = math.log(Ij / (g[j] * A[j]))
    return (E[i] - E[j]) / (kB * (yj - yi))

# --- multi-line OLS Boltzmann plot ---
def _mean(xs):
    return sum(xs) / len(xs)

def ols_intercept(E, y):
    eb, yb = _mean(E), _mean(y)
    num = sum((ek - eb) * (yk - yb) for ek, yk in zip(E, y))
    den = sum((ek - eb) ** 2 for ek in E)
    slope = num / den
    return yb - slope * eb

def ols_density(kB, T, Fcal, g, E, A, I):
    y = [math.log(I[k] / (g[k] * A[k])) for k in range(len(I))]
    return math.exp(ols_intercept(E, y)) * partition_function(kB, T, g, E) / Fcal

# --- self-absorption correction ---
def self_absorption_factor(tau):
    return 1.0 if tau == 0.0 else (1.0 - math.exp(-tau)) / tau

def self_absorbed_density(kB, T, Fcal, g, E, A, u, tau, Imeas):
    return classic_density(kB, T, Fcal, g, E, A, u, Imeas / self_absorption_factor(tau))

# --- Saha factor ---
def thermal_bracket(kB, T, me, h):
    return 2.0 * math.pi * me * kB * T / (h * h)

def saha_factor(kB, T, me, h, chi, gZ, EZ, gZ1, EZ1):
    return (2.0 * (partition_function(kB, T, gZ1, EZ1) / partition_function(kB, T, gZ, EZ))
            * thermal_bracket(kB, T, me, h) ** 1.5
            * math.exp(-chi / (kB * T)))

def electron_density_from_ratio(kB, T, me, h, chi, gZ, EZ, gZ1, EZ1, R):
    return saha_factor(kB, T, me, h, chi, gZ, EZ, gZ1, EZ1) / R
# ===================================================================================


def approx(a, b, rtol=RTOL):
    return abs(a - b) <= rtol * max(1.0, abs(b))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "fixtures.json")) as f:
        fx = json.load(f)
    g_ = fx["global"]
    kB, T, Fcal = g_["kB"], g_["T"], g_["Fcal"]
    fails = []

    def check(name, cond, detail=""):
        print(f"  [{'PASS' if cond else 'FAIL'}] {name}" + ((" — " + detail) if (detail and not cond) else ""))
        if not cond:
            fails.append(name)

    for sc in fx["scenarios"]:
        ch = sc["checks"]
        print(f"\n=== scenario: {sc['name']} ===")

        if sc["kind"] == "multi-element-composition":
            els = sc["elements"]

            print(f"forward  ({ch['forward']['theorem']})")
            for e in els:
                for k, expected in enumerate(e["intensities"]):
                    got = line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], k)
                    check(f"{e['sym']}.intensity[{k}]", approx(got, expected), f"got {got} vs {expected}")
                check(f"{e['sym']}.U", approx(partition_function(kB, T, e["g"], e["E"]), e["partitionFunction"]))

            print(f"round_trip  ({ch['round_trip']['theorem']})")
            for idx, e in enumerate(els):
                I = line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], e["u"])
                rec = classic_density(kB, T, Fcal, e["g"], e["E"], e["A"], e["u"], I)
                check(f"recover {e['sym']}.N", approx(rec, e["N"]), f"got {rec} vs {e['N']}")

            print(f"temperature  ({ch['temperature']['theorem']})")
            for idx, e in enumerate(els):
                I0 = line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], 0)
                I1 = line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], 1)
                Trec = recover_T(kB, e["g"], e["E"], e["A"], 0, 1, I0, I1)
                check(f"recover T from {e['sym']}", approx(Trec, ch["temperature"]["true_T"][idx]))

            print(f"ols  ({ch['ols']['theorem']})")
            ols_dens = []
            for e in els:
                I = [line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], k) for k in range(len(e["g"]))]
                d = ols_density(kB, T, Fcal, e["g"], e["E"], e["A"], I)
                ols_dens.append(d)
                check(f"OLS recover {e['sym']}.N (all lines)", approx(d, e["N"]), f"got {d} vs {e['N']}")
            ols_comp = [composition(ols_dens, i) for i in range(len(els))]
            for i, e in enumerate(els):
                check(f"OLS composition[{i}] == classic/true", approx(ols_comp[i], sc["true_composition"][i]))

            print(f"self_absorbed  ({ch['self_absorbed']['theorem']})")
            sa_dens = []
            for e in els:
                thin = line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], e["u"])
                thick = thin * self_absorption_factor(e["tau"])
                d = self_absorbed_density(kB, T, Fcal, e["g"], e["E"], e["A"], e["u"], e["tau"], thick)
                sa_dens.append(d)
                check(f"self-absorbed recover {e['sym']}.N (thick+tau)", approx(d, e["N"]), f"got {d} vs {e['N']}")
            sa_comp = [composition(sa_dens, i) for i in range(len(els))]
            for i in range(len(els)):
                check(f"self-absorbed composition[{i}] == true", approx(sa_comp[i], sc["true_composition"][i]))

            print(f"closure  ({ch['closure']['theorem']})")
            dens = [classic_density(kB, T, Fcal, e["g"], e["E"], e["A"], e["u"],
                                    line_intensity(kB, T, e["N"], Fcal, e["g"], e["E"], e["A"], e["u"])) for e in els]
            comp = [composition(dens, i) for i in range(len(dens))]
            for i, e in enumerate(els):
                check(f"composition[{i}] ({e['sym']}) == true", approx(comp[i], ch["closure"]["true_composition"][i]),
                      f"got {comp[i]} vs {ch['closure']['true_composition'][i]}")
            check("sum(composition) == 1", approx(sum(comp), 1.0), f"sum = {sum(comp)}")

            print(f"calibration_free  ({ch['calibration_free']['theorem']})")
            cf = ch["calibration_free"]
            scale = cf["Fcal_scale"]

            def comp_with(fc):
                d = [classic_density(kB, T, fc, e["g"], e["E"], e["A"], e["u"],
                                     line_intensity(kB, T, e["N"], fc, e["g"], e["E"], e["A"], e["u"])) for e in els]
                return [composition(d, i) for i in range(len(d))]

            base, scaled = comp_with(Fcal), comp_with(Fcal * scale)
            for i in range(len(base)):
                check(f"composition invariant under Fcal x{scale:g} [{i}]", approx(base[i], scaled[i]))

        elif sc["kind"] == "saha-boltzmann":
            cc = sc["constants"]
            me, h, chi = cc["me"], cc["h"], cc["chi"]
            nz, ion = sc["neutral"], sc["ion"]

            print(f"temperature  ({ch['temperature']['theorem']})")
            Trec = recover_T(kB, nz["g"], nz["E"], nz["A"], 0, 1, nz["intensities"][0], nz["intensities"][1])
            check("recover T (neutral 2-line slope)", approx(Trec, ch["temperature"]["true_T"]),
                  f"got {Trec} vs {ch['temperature']['true_T']}")

            print(f"saha  ({ch['saha']['theorem']})")
            sa = ch["saha"]
            Nz_rec = classic_density(kB, T, Fcal, nz["g"], nz["E"], nz["A"], nz["u"], nz["intensities"][nz["u"]])
            Nz1_rec = classic_density(kB, T, Fcal, ion["g"], ion["E"], ion["A"], ion["u"], ion["intensities"][ion["u"]])
            R = Nz1_rec / Nz_rec
            S = saha_factor(kB, T, me, h, chi, nz["g"], nz["E"], ion["g"], ion["E"])
            ne_rec = electron_density_from_ratio(kB, T, me, h, chi, nz["g"], nz["E"], ion["g"], ion["E"], R)
            check("sahaFactor S(T) matches fixture", approx(S, sa["sahaFactor"]), f"got {S} vs {sa['sahaFactor']}")
            check("stage ratio R matches fixture", approx(R, sa["stage_ratio"]), f"got {R} vs {sa['stage_ratio']}")
            check("recover n_e = S/R == true n_e", approx(ne_rec, sa["true_ne"]), f"got {ne_rec} vs {sa['true_ne']}")
            check("Saha law R*n_e == S(T)", approx(R * ne_rec, S), f"{R * ne_rec} vs {S}")

        else:
            check(f"unknown scenario kind '{sc['kind']}'", False)

    print()
    if fails:
        print(f"FAILED: {len(fails)} check(s): {', '.join(fails)}")
        sys.exit(1)
    print("ALL CHECKS PASSED — implementation matches the verified-spec fixtures.")
    sys.exit(0)


if __name__ == "__main__":
    main()
