/-
Copyright (c) 2026 Brian Squires. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Brian Squires
-/
import Mathlib
import CflibsFormal.Boltzmann
import CflibsFormal.ForwardMap
import CflibsFormal.Closure
import CflibsFormal.Identifiability

/-!
# CF-LIBS formalization — the classic calibration-free algorithm, assembled and sound

This module assembles the classical calibration-free CF-LIBS (CF-LIBS) algorithm
end-to-end as an *explicit estimator* and proves it **sound**: when the line
intensities are generated by the forward model at true parameters `(T, N_s)`, the
estimator returns exactly the true composition `C_s = N_s / Σ_t N_t`.

The procedure on measured line intensities at unknown `(T, {N_s})`:

1. **Temperature (slope).** Per species build the intensity Boltzmann plot
   `y_k = log (I_k / (g_k A_k))` against `E_k`; its slope `-1/(k_B T)` recovers `T`.
   This is exactly `ForwardMap.boltzmann_plot_intensity` /
   `ForwardMap.temperature_from_two_lines`, restated here as
   `classic_temperature_correct`.
2. **Relative densities (intercept).** Exponentiating the plot intercept recovers
   `Fcal · N_s / U_s(T)`; dividing out the (known once `T` is fixed) partition
   function `U_s` and the shared calibration `Fcal` gives `N_s` up to the common
   scale. We package the explicit per-species algebraic inverse of the forward
   line-emission step as `classicDensity`.
3. **Closure (absolute scale).** Impose `∑_s C_s = 1` via the closure map
   `Closure.composition`. This is the only place the absolute scale is fixed; the
   unknown shared `Fcal` cancels in the ratio — the *calibration-free* property,
   made literally true by `Closure.composition_smul_invariant`
   (`classic_calibration_free`).

Everything reuses the already-proven forward defs and closure facts verbatim;
soundness is the assembly (`classic_sound`), not a reproof.

Scope: the clean case — shared `Fcal`, one chosen emitting upper level per species
(`u s`), positive degeneracies / Einstein coefficients, positive total density.
-/

namespace CflibsFormal.Classic

open CflibsFormal
open Finset Real
open scoped BigOperators

variable {ι : Type*} [Fintype ι]
variable {κ : Type*} [Fintype κ]

/-- **Step (1)–(2) packaged as a function of the data.** The explicit per-species
algebraic inverse of the forward line-emission step. Reads the species total number
density `N_s` back from a *single* measured line intensity `I` on emitting upper
level `u`, given the recovered temperature `T`, the shared calibration `Fcal`, the
partition function `U_s(T) = partitionFunction kB T g E` (computable from atomic data
once `T` is known), the degeneracy `g u`, the Einstein coefficient `A u`, and the
energy `E u`:
  `classicDensity = I · U / (Fcal · A_u · g_u · bf)`.
Since `lineIntensity kB T N Fcal g E A u = Fcal · A_u · (N · g_u · bf / U)`, inverting
gives `N = I · U / (Fcal · A_u · g_u · bf)`. Equivalently this exponentiates the
intensity-Boltzmann-plot intercept `q_s = log (Fcal · N_s / U_s)` and rescales; we keep
the closed division form so soundness is a single `field_simp` inverse. -/
noncomputable def classicDensity (kB T Fcal : ℝ) (g E A : ι → ℝ) (u : ι) (I : ℝ) : ℝ :=
  I * partitionFunction kB T g E / (Fcal * A u * g u * boltzmannFactor kB T (E u))

/-- **Step (3): the full classic CF-LIBS composition estimator.** For each species `s`
(index type `κ`) it inverts that species' chosen emitting line `I s` on upper level
`u s` with per-species atomic data `g s, E s, A s` (each `ι → ℝ` over the shared
level-index type `ι`), producing the recovered relative density `classicDensity …`,
then applies the closure map `composition` (from `Closure.lean`) which divides by the
total recovered density. The closure step fixes the absolute scale: the shared but
unknown `Fcal` cancels in the ratio, so NO external calibration standard enters — the
calibration-free property, made literally true by `composition_smul_invariant`.
`classicComposition` is a pure function of `(T, atomic data, intensities)`; `T` itself
is recovered upstream by `temperature_from_two_lines` (boltzmann-plot slope), reused
not redefined. -/
noncomputable def classicComposition (kB T Fcal : ℝ) (g E A : κ → ι → ℝ)
    (u : κ → ι) (I : κ → ℝ) (s : κ) : ℝ :=
  composition (fun t => classicDensity kB T Fcal (g t) (E t) (A t) (u t) (I t)) s

/-- **Per-species soundness core.** The exact inverse of the forward line-emission
step: feeding the forward intensity `lineIntensity kB T N Fcal g E A u` back through
`classicDensity` recovers the true total density `N`. The partition function `U`, the
calibration `Fcal`, the Einstein coefficient `A_u`, the degeneracy `g_u`, and the
Boltzmann factor `bf` all cancel. Everything downstream (composition soundness,
calibration-free) is assembled from this single equality. -/
theorem classicDensity_recovers [Nonempty ι] {kB T N Fcal : ℝ} {g E A : ι → ℝ}
    (hg : ∀ k, 0 < g k) (hFcal : 0 < Fcal) (u : ι) (hA : 0 < A u) :
    classicDensity kB T Fcal g E A u (lineIntensity kB T N Fcal g E A u) = N := by
  have hU : 0 < partitionFunction kB T g E := partitionFunction_pos hg
  have hUne : partitionFunction kB T g E ≠ 0 := hU.ne'
  have hFne : Fcal ≠ 0 := hFcal.ne'
  have hAne : A u ≠ 0 := hA.ne'
  have hgne : g u ≠ 0 := (hg u).ne'
  have hbf : boltzmannFactor kB T (E u) ≠ 0 := (boltzmannFactor_pos _ _ _).ne'
  unfold classicDensity lineIntensity population
  field_simp

/-- **MAIN THEOREM — end-to-end soundness of the classic CF-LIBS algorithm.** When the
intensities are generated by the forward model at true parameters `(T, N)`,
`classicComposition` returns exactly the true composition `C_s = N_s / Σ_t N_t`. The
per-species recovery `classicDensity_recovers` fires for every species, so the recovered
density vector equals `N` pointwise; feeding it into the existing closure map
`composition` matches the true composition. Soundness is the assembly. -/
theorem classic_sound [Nonempty ι] [Nonempty κ] {kB T Fcal : ℝ}
    {N : κ → ℝ} {g E A : κ → ι → ℝ} {u : κ → ι}
    (hg : ∀ s k, 0 < g s k) (hFcal : 0 < Fcal) (hA : ∀ s, 0 < A s (u s))
    (_hN : 0 < totalDensity N) (s : κ) :
    classicComposition kB T Fcal g E A u
        (fun t => lineIntensity kB T (N t) Fcal (g t) (E t) (A t) (u t)) s
      = composition N s := by
  unfold classicComposition
  have hrec : (fun t => classicDensity kB T Fcal (g t) (E t) (A t) (u t)
      (lineIntensity kB T (N t) Fcal (g t) (E t) (A t) (u t))) = N :=
    funext (fun t => classicDensity_recovers (hg t) hFcal (u t) (hA t))
  rw [hrec]

/-- **Normalization corollary.** The recovered compositions sum to one, exercising
the positivity of the total density through `composition_sum_one`. -/
theorem classic_sound_sum_one [Nonempty ι] [Nonempty κ] {kB T Fcal : ℝ}
    {N : κ → ℝ} {g E A : κ → ι → ℝ} {u : κ → ι}
    (hg : ∀ s k, 0 < g s k) (hFcal : 0 < Fcal) (hA : ∀ s, 0 < A s (u s))
    (hN : 0 < totalDensity N) :
    ∑ s, classicComposition kB T Fcal g E A u
        (fun t => lineIntensity kB T (N t) Fcal (g t) (E t) (A t) (u t)) s = 1 := by
  have h : ∀ s, classicComposition kB T Fcal g E A u
      (fun t => lineIntensity kB T (N t) Fcal (g t) (E t) (A t) (u t)) s
      = composition N s := fun s => classic_sound hg hFcal hA hN s
  rw [Finset.sum_congr rfl (fun s _ => h s)]
  exact composition_sum_one hN

/-- **Temperature-correctness leg of soundness.** The slope of the intensity Boltzmann
plot built from two measured lines of the same species recovers `1 / (k_B T)` exactly:
the recovered temperature equals the true `T`. Pure reuse of
`temperature_from_two_lines` from `ForwardMap.lean`, restated in the Classic namespace
to articulate that STEP (1) of the classic algorithm is sound. -/
theorem classic_temperature_correct [Nonempty ι] {kB T N Fcal : ℝ} {g E A : ι → ℝ}
    (hg : ∀ k, 0 < g k) (hN : 0 < N) (hFcal : 0 < Fcal) (hA : ∀ k, 0 < A k)
    (i j : ι) (hE : E i ≠ E j) :
    (Real.log (lineIntensity kB T N Fcal g E A j / (g j * A j))
        - Real.log (lineIntensity kB T N Fcal g E A i / (g i * A i))) / (E i - E j)
      = 1 / (kB * T) :=
  temperature_from_two_lines hg hN hFcal hA i j hE

/-- **Calibration-free property.** An unknown common calibration scale `c` on `Fcal`
does NOT change the reported composition: only the closure `∑ C_s = 1` fixes the
absolute scale. Scaling `Fcal` by `c` scales every `classicDensity` by `1/c`, and
`composition` is invariant under a common nonzero rescaling
(`composition_smul_invariant`). The invariance holds for ALL data (no positivity on
`Fcal`, `A`, `g`, or the partition function is needed): the unknown common scale cancels
even in degenerate/zero cases, given only `c ≠ 0`. This is the defining CF-LIBS property
— no external calibration standard enters. -/
theorem classic_calibration_free [Nonempty ι] [Nonempty κ] {kB T Fcal c : ℝ}
    {g E A : κ → ι → ℝ} {u : κ → ι} {I : κ → ℝ}
    (hc : c ≠ 0) (s : κ) :
    classicComposition kB T (c * Fcal) g E A u I s
      = classicComposition kB T Fcal g E A u I s := by
  unfold classicComposition
  have hscale : (fun t => classicDensity kB T (c * Fcal) (g t) (E t) (A t) (u t) (I t))
      = (fun t => (1 / c) * classicDensity kB T Fcal (g t) (E t) (A t) (u t) (I t)) := by
    funext t
    unfold classicDensity
    field_simp
  rw [hscale]
  exact composition_smul_invariant (one_div_ne_zero hc) s

end CflibsFormal.Classic
