#!/usr/bin/env python3
"""Generate the derived parts of the theorem-card tree for cflibs-formal (IA-proposal §1.3, §1.4,
§2, §4.1; owner decisions D21/D23/D24).

Inputs (never written by this script):
  docs/catalog.jsonl            one JSON object per line (CATALOG CONTRACT), sorted by "name"
  docs/scope-tags.tsv           curated: module.lean <TAB> name <TAB> tag <TAB> citation
  docs/scope-published.tsv      generated by `lake exe scope-check --write`: module <TAB> name
                                 <TAB> kind <TAB> own <TAB> published <TAB> via
  docs/citation-whitelist.tsv   curated: citation <TAB> status <TAB> year <TAB> evidence
  docs/theorems/<id>.md         curated cards: YAML front matter + prose (schema in check_cards.py)
  docs/theorems/registry/cards.yaml   (optional) planned-declaration coverage list, for README.md

Outputs (this is the ONLY script that writes them):
  docs/theorems/<id>.md          the block between the BEGIN/END facts markers, regenerated
                                  in place (inserted right after the H1 title if absent)
  docs/theorems/README.md        index by frontier id / published tag / pipeline status + coverage
  docs/theorems/open-items.md    roll-up of every card's open_items

Idempotent: running twice with no other change to the inputs changes no byte of any output.

    scripts/gen_cards.py [--catalog PATH] [--cards-dir PATH] [--root PATH]
    scripts/gen_cards.py --stamp <id> [--catalog PATH] [--cards-dir PATH] [--root PATH]

`--stamp <id>` writes the CURRENT statement hash of docs/theorems/<id>.md's headline + members
into its `lean.reviewed.statement_hash`, and the current `git rev-parse HEAD` into
`lean.reviewed.commit`. It is a surgical text patch of those two lines only (not a YAML dump —
a full re-dump would destroy front-matter comments and formatting), so `lean: reviewed:` must
already exist as a block-style mapping (the card author fills `by`/`method` by hand as part of
the D24 review; `--stamp` fills only what a machine can compute).

No new dependency beyond PyYAML (see `require_yaml` below), matching AGENTS.md's mathlib-only
non-negotiable (which binds `CflibsFormal/*.lean`, not the docs tooling) and the repo's existing
dependency-light Python CI style (`scripts/gen_docs.py`, `scripts/check-citations.sh`).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys
from collections import defaultdict

try:
    import yaml
except ImportError:  # pragma: no cover - exercised via require_yaml()
    yaml = None

FACTS_BEGIN = "<!-- BEGIN GENERATED facts -->"
FACTS_END = "<!-- END GENERATED facts -->"

WHITELIST_BADGE = {
    "VERIFIED": "✅", "CORRECTED": "✅", "AUDIT-VETTED": "\U0001f7e1",
    "UNVERIFIED": "⚠️", "SUSPECT": "⛔", "CONVENTION": "\U0001f4d8",
}


class CardError(Exception):
    """A single card is malformed enough that it cannot be processed further."""


def require_yaml() -> None:
    if yaml is None:
        sys.exit(
            "gen_cards: PyYAML is not installed (`python3 -c \"import yaml\"` failed). "
            "Card front matter cannot be parsed without it. Install it (the CI-pinned `pyyaml`) "
            "before running this script — no vendored fallback (IA-proposal §4.1)."
        )


# ---------------------------------------------------------------------------------------------
# Catalog / TSV loading — shared with check_cards.py.
# ---------------------------------------------------------------------------------------------

def load_catalog(path: pathlib.Path) -> dict[str, dict]:
    """docs/catalog.jsonl -> {fully qualified name: record}. Raises on a malformed line/dup name
    (fail-closed: a broken catalog line must never be silently skipped)."""
    by_name: dict[str, dict] = {}
    with open(path, encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError as e:
                raise CardError(f"{path}:{lineno}: invalid JSON ({e})") from e
            name = rec.get("name")
            if not name:
                raise CardError(f"{path}:{lineno}: record has no \"name\"")
            if name in by_name:
                raise CardError(f"{path}:{lineno}: duplicate catalog record for {name!r}")
            by_name[name] = rec
    return by_name


def build_used_by(catalog: dict[str, dict]) -> dict[str, int]:
    """name -> count of OTHER catalog records whose usedConstants include it."""
    counts: dict[str, int] = defaultdict(int)
    for rec in catalog.values():
        for used in rec.get("usedConstants") or []:
            if used != rec["name"]:
                counts[used] += 1
    return counts


def resolve_name(name: str, catalog: dict[str, dict]) -> tuple[str | None, list[str]]:
    """ScopeCheck-style suffix resolution (tools/ScopeCheck.lean's `shortName`, generalized):
    exact match first; else the set of catalog names equal to, or dot-suffixed by, `name`. Returns
    (resolved name or None, all candidates) — the caller decides NOT-FOUND (empty) vs AMBIGUOUS
    (>1) so the two get distinct, fail-closed error messages."""
    if name in catalog:
        return name, [name]
    candidates = sorted(n for n in catalog if n.endswith("." + name))
    if len(candidates) == 1:
        return candidates[0], candidates
    return None, candidates


def scope_lookup_keys(record: dict) -> tuple[str, str, str]:
    """A catalog record's (module_rel, qualified, leaf) for matching against docs/scope-tags.tsv
    / docs/scope-published.tsv rows, whose `name` column is the BARE declared identifier (as
    scripts/gen_docs.py's RESULT_RE/DEF_RE capture it from source), not the fully qualified name —
    so `CflibsFormal.Alt.csigma_master_line` must match a row named `csigma_master_line` under
    module `Alt/CSigma.lean`, not `Alt.csigma_master_line`. `qualified` is tried first (covers the
    common case where the namespace equals `CflibsFormal` exactly, so qualified == leaf already);
    `leaf` is the fallback for a deeper namespace such as `CflibsFormal.Alt`."""
    file_ = record.get("file") or ""
    module_rel = file_[len("CflibsFormal/"):] if file_.startswith("CflibsFormal/") else file_
    name = record["name"]
    qualified = name[len("CflibsFormal."):] if name.startswith("CflibsFormal.") else name
    leaf = qualified.rsplit(".", 1)[-1]
    return module_rel, qualified, leaf


def load_scope_tags(path: pathlib.Path) -> dict[tuple[str, str], tuple[str, str]]:
    """(module_rel, name) -> (tag, citation). Malformed/comment rows are skipped (validated
    elsewhere by scripts/gen_docs.py / lake exe scope-check); a missing file is a hard error."""
    out: dict[tuple[str, str], tuple[str, str]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 4:
            continue
        module, name, tag, cite = parts
        out[(module, name)] = (tag, cite)
    return out


def load_scope_published(path: pathlib.Path) -> dict[tuple[str, str], tuple[str, str, str, str]]:
    """(module_rel, name) -> (kind, own, published, via). Empty dict if the file does not exist
    yet (a fresh checkout before the first `lake exe scope-check --write`)."""
    out: dict[tuple[str, str], tuple[str, str, str, str]] = {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) == 6:
            module, name, kind, own, published, via = parts
            out[(module, name)] = (kind, own, published, via)
    return out


def scope_row(record: dict, scope_tags) -> tuple[str, str] | None:
    module_rel, qualified, leaf = scope_lookup_keys(record)
    return scope_tags.get((module_rel, qualified)) or scope_tags.get((module_rel, leaf))


def published_row(record: dict, scope_pub):
    module_rel, qualified, leaf = scope_lookup_keys(record)
    return scope_pub.get((module_rel, qualified)) or scope_pub.get((module_rel, leaf))


def load_whitelist(path: pathlib.Path) -> dict[str, str]:
    """citation key -> status."""
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 2 and parts[0] not in out:   # first row wins; check-citations.sh
            out[parts[0]] = parts[1]                  # fails on a duplicate key
    return out


# ---------------------------------------------------------------------------------------------
# statement_hash — the exact contract from the task brief, computed only here (never in Lean).
# ---------------------------------------------------------------------------------------------

def compute_statement_hash(records_in_order: list[dict]) -> str:
    h = hashlib.sha256()
    for r in records_in_order:
        h.update(r["name"].encode("utf-8"))
        h.update(b"\n")
        h.update((r.get("type") or "").encode("utf-8"))
        h.update(b"\n")
        h.update(",".join(r.get("binders") or []).encode("utf-8"))
        h.update(b"\n")
    return h.hexdigest()


# ---------------------------------------------------------------------------------------------
# Card front matter: split / parse. (check_cards.py imports these too.)
# ---------------------------------------------------------------------------------------------

def split_front_matter(text: str) -> tuple[str, str]:
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise CardError("no YAML front matter: file must start with a '---' line")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise CardError("unterminated YAML front matter (no closing '---' line)")
    return "".join(lines[1:end]), "".join(lines[end + 1:])


def load_card(path: pathlib.Path) -> tuple[dict, str, str]:
    """-> (front_matter_dict, body_markdown, raw_fm_text). Raises CardError."""
    text = path.read_text(encoding="utf-8")
    fm_text, body = split_front_matter(text)
    require_yaml()
    try:
        fm = yaml.safe_load(fm_text)
    except yaml.YAMLError as e:
        raise CardError(f"YAML parse error: {e}") from e
    if not isinstance(fm, dict):
        raise CardError("front matter did not parse to a mapping")
    return fm, body, fm_text


def member_decl_name(m) -> str:
    return m["decl"] if isinstance(m, dict) else m


def ordered_decls(fm: dict) -> list[tuple[str, str]]:
    """[(label, declared-name-as-written)], headline first then lean.members in file order."""
    decl = (fm.get("lean") or {}).get("decl")
    out = [("headline", decl)] if decl else []
    for m in (fm.get("lean") or {}).get("members") or []:
        out.append(("member", member_decl_name(m)))
    return out


# Non-card markdown files that may legitimately sit directly under `docs/theorems/`: the two
# files this script itself generates, and the normative schema doc (`docs/theorems/SCHEMA.md`) —
# a fixed reference document, not a curated card, so it carries no YAML front matter.
NON_CARD_FILES = {"README.md", "open-items.md", "SCHEMA.md"}


def iter_card_paths(cards_dir: pathlib.Path) -> list[pathlib.Path]:
    if not cards_dir.exists():
        return []
    out = []
    for p in sorted(cards_dir.glob("*.md")):
        if p.name.startswith("_") or p.name in NON_CARD_FILES:
            continue
        out.append(p)
    return out


# ---------------------------------------------------------------------------------------------
# Facts block rendering.
# ---------------------------------------------------------------------------------------------

def fmt_axioms(axioms: list[str]) -> str:
    return ", ".join(f"`{a}`" for a in axioms) if axioms else "*(none)*"


def render_decl_facts(label: str, record: dict, scope_tags, scope_pub, whitelist,
                       used_by: dict[str, int]) -> str:
    row = scope_row(record, scope_tags)
    tag, cite = row if row else (None, "—")
    pub = published_row(record, scope_pub)
    if pub:
        _kind, own, published, via = pub
    else:
        own, published, via = (tag or "UNTAGGED"), (tag or "UNTAGGED"), "—"

    lines = [f"### {label.capitalize()} — `{record['name']}` ({record['kind']})", ""]
    if record.get("line") is not None:
        link = f"../../{record['file']}#L{record['line']}"
        lines.append(f"- Lean: [`{record['file']}:{record['line']}`]({link})")
    else:
        lines.append(f"- Lean: `{record['file']}` (no source line recorded)")
    if not row:
        lines.append("- Scope: *(no `docs/scope-tags.tsv` row found for this declaration)*")
    elif own != published:
        vias = ", ".join(f"`{v}`" for v in via.split(",")) if via and via != "—" else "—"
        lines.append(f"- Scope: `{own} → {published}` (via {vias})")
    else:
        lines.append(f"- Scope: `{own}`")
    if cite and cite != "—":
        status = whitelist.get(cite, "NOT-IN-WHITELIST")
        badge = WHITELIST_BADGE.get(status, "❓")
        lines.append(f"- Citation: `{cite}` {badge} {status}")
    if record["kind"] == "theorem":
        lines.append(f"- Axioms: {fmt_axioms(record.get('axioms') or [])}")
    lines.append(f"- Used by: {used_by.get(record['name'], 0)} declaration(s) in `CflibsFormal`")
    lines.append("")
    lines.append("```lean")
    lines.append((record.get("type") or "").rstrip("\n"))
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def build_facts_block(fm: dict, catalog, scope_tags, scope_pub, whitelist, used_by) -> str:
    parts = [FACTS_BEGIN, "",
              "**Facts** — generated by `scripts/gen_cards.py`; hand edits inside this "
              "block are overwritten on the next run.", ""]
    order: list[tuple[str, str]] = []
    unresolved: list[str] = []
    for label, name in ordered_decls(fm):
        resolved, candidates = resolve_name(name, catalog)
        if resolved:
            order.append((label, resolved))
        else:
            what = "no match" if not candidates else f"ambiguous: {', '.join(candidates)}"
            unresolved.append(f"{label} `{name}` did not resolve in the catalog ({what})")

    for label, name in order:
        parts.append(render_decl_facts(label, catalog[name], scope_tags, scope_pub, whitelist,
                                        used_by))

    if order:
        current_hash = compute_statement_hash([catalog[n] for _l, n in order])
        reviewed = ((fm.get("lean") or {}).get("reviewed")) or {}
        reviewed_hash = reviewed.get("statement_hash")
        if not reviewed_hash:
            status = "**UNREVIEWED**"
        elif reviewed_hash == current_hash:
            status = "**MATCH**"
        else:
            status = "**STALE** — LaTeX must be re-reviewed and the card re-stamped"
        commit_note = f" (reviewed at commit `{reviewed['commit']}`)" if reviewed.get("commit") \
            else ""
        parts.append(f"Statement hash: `{current_hash}` — {status} vs "
                      f"`lean.reviewed.statement_hash`{commit_note}.")
    for msg in unresolved:
        parts.append(f"⚠️ {msg}.")
    parts.append("")
    parts.append(FACTS_END)
    return "\n".join(parts)


def upsert_facts(text: str, block: str) -> str:
    if FACTS_BEGIN in text and FACTS_END in text:
        pattern = re.compile(re.escape(FACTS_BEGIN) + r".*?" + re.escape(FACTS_END), re.S)
        # `block` is returned verbatim (a callable replacement is never treated as a backreference
        # template), so a Lean type containing a literal backslash round-trips unchanged.
        return pattern.sub(lambda _m: block, text, count=1)
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("# "):
            head = "".join(lines[: i + 1])
            rest = "".join(lines[i + 1:]).lstrip("\n")
            return f"{head}\n{block}\n\n{rest}"
    raise CardError("no H1 title line ('# ...') found to anchor the generated facts block")


def regenerate_card_facts(path: pathlib.Path, catalog, scope_tags, scope_pub, whitelist,
                           used_by) -> bool:
    """Returns True if the file changed on disk."""
    text = path.read_text(encoding="utf-8")
    fm, _body, _fm_text = load_card(path)
    block = build_facts_block(fm, catalog, scope_tags, scope_pub, whitelist, used_by)
    new_text = upsert_facts(text, block)
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
        return True
    return False


# ---------------------------------------------------------------------------------------------
# --stamp: surgical patch of lean.reviewed.{statement_hash,commit}.
# ---------------------------------------------------------------------------------------------

def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def patch_reviewed_block(fm_text: str, new_hash: str, sha: str) -> str:
    """Replaces (or inserts) the `statement_hash:`/`commit:` children of the block-style
    `lean: reviewed:` mapping, byte-for-byte elsewhere. Deliberately not a YAML re-dump: that
    would reformat the whole front matter and destroy comments. Requires `reviewed:` to already
    exist as a block mapping (the card author fills `by`/`method` as part of the D24 review, then
    `--stamp` fills what a machine can compute)."""
    lines = fm_text.splitlines(keepends=True)
    lean_idx = next((i for i, l in enumerate(lines) if re.match(r"^lean:\s*$", l)), None)
    if lean_idx is None:
        raise CardError("front matter has no top-level, block-style 'lean:' mapping")
    lean_end = len(lines)
    for j in range(lean_idx + 1, len(lines)):
        l = lines[j]
        if l.strip() == "" or l.lstrip().startswith("#"):
            continue
        if _indent_of(l) == 0:
            lean_end = j
            break
    block = lines[lean_idx:lean_end]

    rev_idx = None
    rev_indent = None
    for k, l in enumerate(block):
        m = re.match(r"^(\s+)reviewed:\s*$", l)
        if m:
            rev_idx, rev_indent = k, len(m.group(1))
            break
    if rev_idx is None:
        raise CardError(
            "no block-style 'lean: reviewed:' mapping found. Add it with 'by:'/'method:' filled "
            "in (the D24 review record) before running --stamp; --stamp fills only "
            "'statement_hash' and 'commit'."
        )
    rev_end = len(block)
    for k in range(rev_idx + 1, len(block)):
        l = block[k]
        if l.strip() == "":
            continue
        if _indent_of(l) <= rev_indent:
            rev_end = k
            break
    child_indent = rev_indent + 2
    pad = " " * child_indent
    rev_children = block[rev_idx + 1:rev_end]

    def set_key(children: list[str], key: str, value: str) -> list[str]:
        pat = re.compile(rf"^ *{re.escape(key)}:\s*.*$")
        for idx, l in enumerate(children):
            if _indent_of(l) == child_indent and pat.match(l):
                children[idx] = f'{pad}{key}: "{value}"\n'
                return children
        children.append(f'{pad}{key}: "{value}"\n')
        return children

    rev_children = set_key(rev_children, "statement_hash", new_hash)
    rev_children = set_key(rev_children, "commit", sha)
    block[rev_idx + 1:rev_end] = rev_children
    lines[lean_idx:lean_end] = block
    return "".join(lines)


def stamp_card(path: pathlib.Path, catalog: dict, root: pathlib.Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    fm_text, body = split_front_matter(text)
    require_yaml()
    fm = yaml.safe_load(fm_text)
    order = []
    for label, name in ordered_decls(fm):
        resolved, candidates = resolve_name(name, catalog)
        if not resolved:
            what = "no match" if not candidates else f"ambiguous: {', '.join(candidates)}"
            raise CardError(f"{label} {name!r} does not resolve in the catalog ({what})")
        order.append(catalog[resolved])
    if not order:
        raise CardError("card has no lean.decl to stamp")
    new_hash = compute_statement_hash(order)
    sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, capture_output=True, text=True,
                          check=True).stdout.strip()
    new_fm_text = patch_reviewed_block(fm_text, new_hash, sha)
    path.write_text("---\n" + new_fm_text + "---\n" + body, encoding="utf-8")
    return new_hash, sha


# ---------------------------------------------------------------------------------------------
# docs/theorems/README.md and open-items.md.
# ---------------------------------------------------------------------------------------------

def load_registry_cards(cards_dir: pathlib.Path):
    """(optional) registry/cards.yaml: {..., cards: [{id, headline, members: [...], ...}, ...]} —
    the Phase-1 plan of which declarations each future card covers, for the README coverage
    count. None if the file is absent (nothing to compare against yet)."""
    path = cards_dir / "registry" / "cards.yaml"
    if not path.exists():
        return None
    require_yaml()
    with open(path, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data


def planned_decls_from_registry(registry) -> set[str]:
    """The declarations `registry/cards.yaml` plans to cover, regardless of whether a card for
    them exists yet. Accepts either shape seen for this (small, hand-maintained, still settling)
    registry: a flat `{id: {planned: [...], headline, members, ...}}` mapping, or `{cards: [{id,
    headline, members, ...}, ...]}`. Prefers an entry's explicit `planned` list; falls back to
    `headline` + `members` when absent, so a card entry cannot silently contribute zero decls."""
    planned: set[str] = set()
    if not isinstance(registry, dict):
        return planned
    if isinstance(registry.get("cards"), list):
        entries = [e for e in registry["cards"] if isinstance(e, dict)]
    else:
        entries = [v for v in registry.values() if isinstance(v, dict)]
    for entry in entries:
        if entry.get("planned"):
            for d in entry["planned"]:
                planned.add(d)
            continue
        if entry.get("headline"):
            planned.add(entry["headline"])
        for m in entry.get("members") or []:
            planned.add(m)
    return planned


def write_readme_and_open_items(cards_dir: pathlib.Path, cards: list[tuple[pathlib.Path, dict]],
                                 catalog: dict, scope_tags, scope_pub):
    by_frontier: dict[str, list[str]] = defaultdict(list)
    by_published: dict[str, list[str]] = defaultdict(list)
    by_pipeline: dict[str, list[str]] = defaultdict(list)
    covered_decls: set[str] = set()

    lines_ro = ["# Theorem cards", "",
                "> **AUTO-GENERATED** by `scripts/gen_cards.py` from `docs/theorems/*.md` "
                "front matter — do not hand-edit; the docs-sync CI gate diffs this "
                "against source.", ""]
    for path, fm in cards:
        cid = fm.get("id", path.stem)
        status = fm.get("status") or {}
        for fid in (fm.get("frontier") or {}).get("ids", []) if isinstance(fm.get("frontier"), dict) else []:
            by_frontier[fid].append(cid)
        # `scope.*` is never authored (SCHEMA.md: generated-only) — derive the headline's
        # published tag the same way the Facts block does, from the catalog + scope-tags.tsv /
        # scope-published.tsv, not from a nonexistent front-matter field.
        pub = "UNKNOWN"
        decl = (fm.get("lean") or {}).get("decl")
        resolved, _c = resolve_name(decl, catalog) if decl else (None, [])
        if resolved:
            rec = catalog[resolved]
            row = scope_row(rec, scope_tags)
            prow = published_row(rec, scope_pub)
            if prow:
                pub = prow[2]  # (kind, own, published, via)
            elif row:
                pub = row[0]
        by_published[pub].append(cid)
        by_pipeline[status.get("pipeline", "UNKNOWN")].append(cid)
        for _label, name in ordered_decls(fm):
            covered_decls.add(name)

    lines_ro.append("## By frontier id")
    lines_ro.append("")
    for fid in sorted(by_frontier):
        ids = ", ".join(f"[`{c}`]({c}.md)" for c in sorted(by_frontier[fid]))
        lines_ro.append(f"- **{fid}**: {ids}")
    lines_ro.append("")
    lines_ro.append("## By published scope tag")
    lines_ro.append("")
    for tag in sorted(by_published):
        ids = ", ".join(f"[`{c}`]({c}.md)" for c in sorted(by_published[tag]))
        lines_ro.append(f"- **{tag}**: {ids}")
    lines_ro.append("")
    lines_ro.append("## By pipeline status")
    lines_ro.append("")
    for status in sorted(by_pipeline):
        ids = ", ".join(f"[`{c}`]({c}.md)" for c in sorted(by_pipeline[status]))
        lines_ro.append(f"- **{status}**: {ids}")
    lines_ro.append("")

    registry = load_registry_cards(cards_dir)
    lines_ro.append("## Coverage")
    lines_ro.append("")
    if registry is None:
        lines_ro.append("`docs/theorems/registry/cards.yaml` not found — planned-declaration "
                         "coverage is not tracked yet (advisory only; see `--require-coverage` "
                         "in `scripts/check_cards.py`).")
    else:
        planned = planned_decls_from_registry(registry)
        missing = sorted(planned - covered_decls)
        lines_ro.append(f"{len(planned) - len(missing)}/{len(planned)} planned declarations have "
                         f"a card ({len(cards)} cards, {len(covered_decls)} declarations "
                         f"covered).")
        if missing:
            lines_ro.append("")
            lines_ro.append("Not yet covered by any card:")
            lines_ro.append("")
            for d in missing:
                lines_ro.append(f"- `{d}`")
    lines_ro.append("")
    (cards_dir / "README.md").write_text("\n".join(lines_ro) + "\n", encoding="utf-8")

    lines_oi = ["# Open items", "",
                "> **AUTO-GENERATED** by `scripts/gen_cards.py`: every card's `open_items`, "
                "rolled up. cflibs-formal has no `.beads/`; this plus optional issue links is "
                "the tracker (IA-proposal §1.3 item 4).", ""]
    any_items = False
    for path, fm in cards:
        cid = fm.get("id", path.stem)
        items = fm.get("open_items") or []
        if not items:
            continue
        any_items = True
        lines_oi.append(f"## [`{cid}`]({cid}.md)")
        lines_oi.append("")
        for item in items:
            if isinstance(item, dict):
                kind = item.get("kind", "?")
                text = item.get("text", "")
                ref = f" ({item['ref']})" if item.get("ref") else ""
                lines_oi.append(f"- **{kind}**: {text}{ref}")
            else:
                lines_oi.append(f"- {item}")
        lines_oi.append("")
    if not any_items:
        lines_oi.append("*(no open items on any card)*")
        lines_oi.append("")
    (cards_dir / "open-items.md").write_text("\n".join(lines_oi) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=pathlib.Path,
                     default=pathlib.Path(__file__).resolve().parent.parent)
    ap.add_argument("--catalog", type=pathlib.Path, default=None)
    ap.add_argument("--cards-dir", type=pathlib.Path, default=None)
    ap.add_argument("--stamp", metavar="ID", default=None,
                     help="stamp docs/theorems/<ID>.md's reviewed.statement_hash + commit, then "
                          "exit (does not regenerate facts blocks or README/open-items.md)")
    args = ap.parse_args(argv)

    root = args.root.resolve()
    catalog_path = args.catalog or (root / "docs" / "catalog.jsonl")
    cards_dir = args.cards_dir or (root / "docs" / "theorems")

    if not catalog_path.exists():
        print(f"gen_cards: catalog not found: {catalog_path}", file=sys.stderr)
        return 1
    catalog = load_catalog(catalog_path)

    if args.stamp:
        card_path = cards_dir / f"{args.stamp}.md"
        if not card_path.exists():
            print(f"gen_cards: no such card: {card_path}", file=sys.stderr)
            return 1
        try:
            new_hash, sha = stamp_card(card_path, catalog, root)
        except CardError as e:
            print(f"gen_cards: --stamp {args.stamp}: {e}", file=sys.stderr)
            return 1
        print(f"gen_cards: stamped {card_path} -> statement_hash={new_hash} commit={sha}")
        return 0

    scope_tags = load_scope_tags(root / "docs" / "scope-tags.tsv")
    scope_pub = load_scope_published(root / "docs" / "scope-published.tsv")
    whitelist = load_whitelist(root / "docs" / "citation-whitelist.tsv")
    used_by = build_used_by(catalog)

    changed = 0
    failed: list[str] = []
    cards: list[tuple[pathlib.Path, dict]] = []
    for path in iter_card_paths(cards_dir):
        try:
            fm, _body, _fm_text = load_card(path)
        except CardError as e:
            failed.append(f"{path}: {e}")
            continue
        cards.append((path, fm))
        try:
            if regenerate_card_facts(path, catalog, scope_tags, scope_pub, whitelist, used_by):
                changed += 1
        except CardError as e:
            failed.append(f"{path}: {e}")

    write_readme_and_open_items(cards_dir, cards, catalog, scope_tags, scope_pub)

    print(f"gen_cards: {len(cards)} card(s) processed, {changed} facts block(s) changed, "
          f"README.md + open-items.md written to {cards_dir}")
    if failed:
        for msg in failed:
            print(f"gen_cards: FAILED {msg}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
